<%@page extends="com.zucchetti.PortalStudio.PortalStudioBaseEditors" %><%@ page import="com.zucchetti.SPBridge.*" %><%@ page import="com.zucchetti.sitepainter.SPPrxycizer" %><%@ page contentType="text/javascript;charset=UTF-8" language="java" pageEncoding="UTF-8" %><%Sitepainter sp=Sitepainter.getSitepainter(request); %>
<%if(sp.isLogged()){ %><script>
  var ZtChartLibs = {
    ZtChartFunctions : '<%=SPPrxycizer.proxycizedPath("ZtChartFunctions.js")%>',
    ZtChartGeoFunctions : '<%=SPPrxycizer.proxycizedPath("ZtChartGeoFunctions.js")%>',
    ZtChartTransDict : '<%=SPPrxycizer.proxycizedPath("ZtChartTransDict.js")%>',
    HamburgerMenuObj : '<%=SPPrxycizer.proxycizedPath("HamburgerMenuObj.js")%>',
    ChartObj : '<%=SPPrxycizer.proxycizedPath("ChartObj.js")%>',
    Std : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartStd.js")%>',
    Lines : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartLines.js")%>',
    Bar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartBar.js")%>',
    StackBar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartStackBar.js")%>',
    Pie : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartPie.js")%>',
    Area : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartArea.js")%>',
    StackArea : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartStackArea.js")%>',
    TreeMap : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartTreeMap.js")%>',
    TreeMapBar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartTreeMapBar.js")%>',
    LayeredBar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartLayeredBar.js")%>',
    Waterfall : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartWaterfall.js")%>',
    Radar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartRadar.js")%>',
    XYZ : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartXYZ.js")%>',
    Pareto : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartPareto.js")%>',
    PyramidDistribution : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartPyramidDistribution.js")%>',
    Word : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartWord.js")%>',
    Dial : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartDial.js")%>',
    Thermo : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartThermo.js")%>',
    Lights : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartLights.js")%>',
    Image : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartImage.js")%>',
    Display : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartDisplay.js")%>',
    MultiDimCursor : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartMultiDimCursor.js")%>',
    Container : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartContainer.js")%>',
    Geographic : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartGeographic.js")%>',
    Aster : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartAster.js")%>',
    AreaBar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartAreaBar.js")%>',
    Sunburst : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartSunburst.js")%>',
    Tree : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartTree.js")%>',
    CirclePack : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartCirclePack.js")%>',
    Force : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartForce.js")%>',
    Matrix : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartMatrix.js")%>',
    Chord : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartChord.js")%>',
    Calendar : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartCalendar.js")%>',
    Pyramid : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartPyramid.js")%>',
    Funnel : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartFunnel.js")%>',
    Mekko : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartMekko.js")%>',
    BCMatrix : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartBCMatrix.js")%>',
    PCoords : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartPCoords.js")%>',
    Voronoi : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartVoronoi.js")%>',
    Sankey : '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartSankey.js")%>',
    RingPerc: '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtChartRingPerc.js")%>',
    ECharts: '<%=SPPrxycizer.proxycizedPath("chart/objects/ZtECharts.js")%>'
  };
</script>
<%} %>
