<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Example:
  <Orig_str>stringa originale</Orig_str>
    <ITA>Traduzione</ITA>
    .
    .
    <JAP><![CDATA[String with special chars: <>&]]></JAP>
    .
    .
    <ENG>Translation</ENG>
-->
<TRANSLATED_STRINGS>
  <Orig_str>password</Orig_str>
    <ENG>Password</ENG>
  <Orig_str> Sintetic</Orig_str>
    <ENG>Short Causal</ENG>
  <Orig_str>+ Soggetti Oper. Conto Terzi</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>- Comunicazione rapporti mensili -</Orig_str>
    <ENG>- Monthly Contracts Communication -</ENG>
  <Orig_str>------------</Orig_str>
  <Orig_str>.Rapporti.</Orig_str>
    <ENG>Contracts</ENG>
  <Orig_str>001. Tabelle Base</Orig_str>
    <ENG>001. Base Tables</ENG>
  <Orig_str>002. Tabelle Antiriciclaggio (UIF)</Orig_str>
    <ENG>002. Anti Laundering Tables (UIF)</ENG>
  <Orig_str>003. Tabelle Agenzia Entrate</Orig_str>
    <ENG>003. Tax Agency Tables</ENG>
  <Orig_str>01. Causali Sintetiche</Orig_str>
    <ENG>04. Short Causal</ENG>
  <Orig_str>01. Import Dati Mensile</Orig_str>
    <ENG>01. Monthly Data Import</ENG>
  <Orig_str>01. Intermediario</Orig_str>
    <ENG>01. Company</ENG>
  <Orig_str>01. Operazioni</Orig_str>
    <ENG>01. Operations</ENG>
  <Orig_str>01. Persone - Societa - Legali Rappresentanti</Orig_str>
    <ENG>01. Identification</ENG>
  <Orig_str>01. Progressivi</Orig_str>
    <ENG>01. Counters</ENG>
  <Orig_str>01. Rapporti</Orig_str>
    <ENG>01. Business Contracts</ENG>
  <Orig_str>01. Rapporti Continuativi</Orig_str>
    <ENG>01. Business Contracts</ENG>
  <Orig_str>01. Rapporti Provvisori</Orig_str>
    <ENG>01. Provisional Business Contracts</ENG>
  <Orig_str>01. Stati</Orig_str>
    <ENG>01. Countries</ENG>
  <Orig_str>01. Tipo Rapporto (Agenzia Entrate)</Orig_str>
    <ENG>14. Contract Type (Financial Agency)</ENG>
  <Orig_str>02. Causali Analitiche</Orig_str>
    <ENG>05. Analytic Causals</ENG>
  <Orig_str>02. Città</Orig_str>
    <ENG>02. Cities</ENG>
  <Orig_str>02. Dipendenze</Orig_str>
    <ENG>02. Agencies</ENG>
  <Orig_str>02. Frazionarie</Orig_str>
    <ENG>02. Transcations under 15000</ENG>
  <Orig_str>02. Frazionate</Orig_str>
    <ENG>02. Transcations under 15000</ENG>
  <Orig_str>02. Gestione Rapporti per Agenzia Entrate</Orig_str>
    <ENG>02. Tax Agency Contracts</ENG>
  <Orig_str>02. Gestione deleghe per Agenzia Entrate</Orig_str>
    <ENG>02. Tax Agency Contracts</ENG>
  <Orig_str>02. Informazioni su Rapporti</Orig_str>
    <ENG>02. Business Contracts Informations</ENG>
  <Orig_str>02. Informazioni sui rapporti</Orig_str>
    <ENG>02. Business Contracts Informations</ENG>
  <Orig_str>02. Rapporti</Orig_str>
    <ENG>02. Business Contracts</ENG>
  <Orig_str>02. Tipo Operazione</Orig_str>
    <ENG>02 Operation Type</ENG>
  <Orig_str>02. Utenti</Orig_str>
    <ENG>02. Users</ENG>
  <Orig_str>03. Aree Geografiche Destinazione Operazioni</Orig_str>
    <ENG>03. Other Destination Geographical Areas</ENG>
  <Orig_str>03. Divise</Orig_str>
    <ENG>03. Currencies</ENG>
  <Orig_str>03. Gestione Op. ExtraConto per Agenzia Entrate</Orig_str>
    <ENG>03 Extra Account Operations for Tax Agency</ENG>
  <Orig_str>03. Import da procedure esterne</Orig_str>
    <ENG>04. Data Import</ENG>
  <Orig_str>03. Informazioni su Rapporti</Orig_str>
    <ENG>02. Business Contracts Informations</ENG>
  <Orig_str>03. Intermediari Controparte</Orig_str>
    <ENG>03. Other Financial Operators</ENG>
  <Orig_str>03. Operazioni</Orig_str>
    <ENG>03. Transactions</ENG>
  <Orig_str>03. Persone - Clienti - Societa - Fornitori</Orig_str>
    <ENG>03. Identifications</ENG>
  <Orig_str>03. Ramo Gruppo</Orig_str>
    <ENG>06. Economic Branches</ENG>
  <Orig_str>03. Rapporti</Orig_str>
    <ENG>03. Business Contracts</ENG>
  <Orig_str>03. Rapporti continuativi</Orig_str>
    <ENG>03. Business Contracts Informations</ENG>
  <Orig_str>03. Stampa Verifica</Orig_str>
    <ENG>03. Check Report</ENG>
  <Orig_str>04. Archivi</Orig_str>
    <ENG>04. Basic Archives</ENG>
  <Orig_str>04. Creazione File per Invio</Orig_str>
    <ENG>04. Tax Agency File Creation</ENG>
  <Orig_str>04. Frazionate</Orig_str>
    <ENG>04. Transcations under 15000</ENG>
  <Orig_str>04. Operazioni</Orig_str>
    <ENG>04. Transcations</ENG>
  <Orig_str>04. Rapporti continuativi</Orig_str>
    <ENG>04. Business Contracts</ENG>
  <Orig_str>04. Riorganizza Indici</Orig_str>
    <ENG>04. Reorder Indexes</ENG>
  <Orig_str>04. Sottogruppi Att.Ec.</Orig_str>
    <ENG>04. Economic Groups</ENG>
  <Orig_str>04. Tipologie Condotta</Orig_str>
    <ENG>04. Behavior Type</ENG>
  <Orig_str>05. Annullamento file inviato</Orig_str>
    <ENG>05. Delete Sended File</ENG>
  <Orig_str>05. Cancellazione UIC</Orig_str>
    <ENG>05. UIC Delete</ENG>
  <Orig_str>05. Frazionate</Orig_str>
    <ENG>05. Transcations under 15000</ENG>
  <Orig_str>05. Ragionevolezza Operazione</Orig_str>
  <Orig_str>05. Ricerca di massa</Orig_str>
    <ENG>05. Analytic Query</ENG>
  <Orig_str>05. Settorizzazione UIC</Orig_str>
    <ENG>05. UIC Sectors</ENG>
  <Orig_str>05. Stampe</Orig_str>
    <ENG>05. Reports</ENG>
  <Orig_str>05. Trasferimenti</Orig_str>
    <ENG>05. Data Tranfers</ENG>
  <Orig_str>06. Azzeramento import dati (6.1)</Orig_str>
    <ENG>06. Nullify data Import (6.1)</ENG>
  <Orig_str>06. Log Applicazione</Orig_str>
    <ENG>06. Procedure Log Viewer</ENG>
  <Orig_str>06. Modalità svolgimento</Orig_str>
    <ENG>06. Unfolding Types</ENG>
  <Orig_str>06. Ricerca dati di massa</Orig_str>
    <ENG>06. Massive research</ENG>
  <Orig_str>06. Stampe</Orig_str>
    <ENG>06. Reports</ENG>
  <Orig_str>06. Tipo Registrazione</Orig_str>
    <ENG>06. Registration Types</ENG>
  <Orig_str>07. Creazione dischetto UIC</Orig_str>
    <ENG>07. UIC Disk Creation</ENG>
  <Orig_str>07. Natura Conti</Orig_str>
    <ENG>07. Account Types</ENG>
  <Orig_str>07. Portal Studio</Orig_str>
  <Orig_str>07. Stampa Anagrafiche per Invio</Orig_str>
    <ENG>07. Identification Report</ENG>
  <Orig_str>08. Allineamenti</Orig_str>
    <ENG>08. Data Manipulation</ENG>
  <Orig_str>08. Storico</Orig_str>
    <ENG>08. Historical Data</ENG>
  <Orig_str>08. Tipi Legami</Orig_str>
    <ENG>11. Link Types</ENG>
  <Orig_str>09. Tipo Documento</Orig_str>
    <ENG>12. Document Types</ENG>
  <Orig_str>09. Trasferimento frazionate su operazioni</Orig_str>
    <ENG>09. Transactions Under 15000 to Full Transaction Transfer</ENG>
  <Orig_str>1. Modifica Data Apertura</Orig_str>
    <ENG>1. Modify Opening Date</ENG>
  <Orig_str>1. Tabelle</Orig_str>
    <ENG>1. Tables</ENG>
  <Orig_str>10. Stampe</Orig_str>
    <ENG>10. Reports</ENG>
  <Orig_str>10. Tipo Intermediario</Orig_str>
    <ENG>13. Company Types</ENG>
  <Orig_str>2. Archivio Unico</Orig_str>
    <ENG>2. A.U.I.</ENG>
  <Orig_str>2. Elimininazione Comunicazione Apertura</Orig_str>
    <ENG>2. Delete Opening Comunication</ENG>
  <Orig_str>3. Archivio Unico</Orig_str>
    <ENG>3. A.U.I.</ENG>
  <Orig_str>3. Elimininazione Comunicazione Apertura</Orig_str>
    <ENG>3. Delete Opening Comunication</ENG>
  <Orig_str>3. Provvisorie</Orig_str>
    <ENG>3. Provisional Data</ENG>
  <Orig_str>4. Modifica Data Chiusura</Orig_str>
    <ENG>4. Modify Closing Date</ENG>
  <Orig_str>4. Provvisorie</Orig_str>
    <ENG>4. Provisional Data</ENG>
  <Orig_str>4. Storico</Orig_str>
    <ENG>5. Historical Data</ENG>
  <Orig_str>5. Elimininazione Comunicazione Chiusura</Orig_str>
    <ENG>5. Delete Closing Date</ENG>
  <Orig_str>5. Regist. AgE.</Orig_str>
    <ENG>5. Financial Agency</ENG>
  <Orig_str>5. Storico</Orig_str>
    <ENG>5. Historical Data</ENG>
  <Orig_str>6. Agenzia delle Entrate</Orig_str>
    <ENG>6. Tax Agency Comunications</ENG>
  <Orig_str>6. Anag. Rapporti (AgE)</Orig_str>
    <ENG>6. Contracts Anagraph (TAX Agency)</ENG>
  <Orig_str>6. Elimininazione Rettifica</Orig_str>
    <ENG>6. Delete Modifing</ENG>
  <Orig_str>7. Anagrafe Rapporti (Agenzia Entrate)</Orig_str>
    <ENG>7. Business Contracts (AgE)</ENG>
  <Orig_str>7. Deleghe/Op.Extra (AgE)</Orig_str>
  <Orig_str>8. Utility</Orig_str>
    <ENG>8. Utilities</ENG>
  <Orig_str>A Cliente</Orig_str>
    <ENG>End Customer</ENG>
  <Orig_str>A Data Chiusura</Orig_str>
    <ENG>End Closing Date</ENG>
  <Orig_str>A Data Informazione</Orig_str>
    <ENG>To Information Date</ENG>
  <Orig_str>A Data Modifica</Orig_str>
    <ENG>End Modification Date</ENG>
  <Orig_str>A Data Operazione</Orig_str>
    <ENG>End Transaction Date</ENG>
  <Orig_str>A Data Variazione</Orig_str>
    <ENG>End Variation Date</ENG>
  <Orig_str>A Data</Orig_str>
    <ENG>To Date</ENG>
  <Orig_str>A Gruppo</Orig_str>
    <ENG>End Branch</ENG>
  <Orig_str>A Rapporto</Orig_str>
    <ENG>End Business Contract</ENG>
  <Orig_str>A Sottogruppo</Orig_str>
    <ENG>End SubGroup</ENG>
  <Orig_str>A01a. Tipo Intermediario</Orig_str>
  <Orig_str>A01b.Codice Intermediario</Orig_str>
  <Orig_str>A03.Identificativo Registrazione</Orig_str>
  <Orig_str>A11.Codice Dipendenza</Orig_str>
  <Orig_str>A12a. CAB Comune Dipendenza</Orig_str>
  <Orig_str>A12b. Comune Dipendenza</Orig_str>
  <Orig_str>A12c. Sigla Provincia Dipendenza</Orig_str>
  <Orig_str>A21. Data Operazione</Orig_str>
  <Orig_str>A22. Flag Frazionata</Orig_str>
  <Orig_str>A23. Flag Contanti</Orig_str>
  <Orig_str>A24. Causale Analitica</Orig_str>
  <Orig_str>A25. Codice Voce</Orig_str>
  <Orig_str>A31a. Tipo Intermediario C/Parte</Orig_str>
  <Orig_str>A31b.Cod. Intermediario C/Parte</Orig_str>
  <Orig_str>A32. Paese Intermediario C/Parte</Orig_str>
  <Orig_str>A33a. CAB Comune Inter. C/Parte</Orig_str>
  <Orig_str>A33b. Comune Inter. C/Parte</Orig_str>
  <Orig_str>A33c. Provincia Inter. C/Parte</Orig_str>
  <Orig_str>A34. Denominazione Inter. C/Parte</Orig_str>
  <Orig_str>A41. Rapporto Continuativo</Orig_str>
  <Orig_str>A42. Flag Rapporto</Orig_str>
  <Orig_str>A43. Tipo Legame Sogg. Operante</Orig_str>
  <Orig_str>A51. Data registrazione</Orig_str>
  <Orig_str>A52a. Tipo Informazione</Orig_str>
  <Orig_str>A52b. Tipo Operazione/Tipo Rapporto</Orig_str>
  <Orig_str>A53. Connessione operazioni</Orig_str>
  <Orig_str>A54a. Codice Stato Registrazione</Orig_str>
  <Orig_str>A54b. Data della rettifica</Orig_str>
  <Orig_str>A54c. Id. Operazione Modificata</Orig_str>
  <Orig_str>A=Attivo / C=Cessato / D=Cancellato</Orig_str>
  <Orig_str>APERTURA DEL RAPPORTO</Orig_str>
    <ENG>CONTRACT OPENING</ENG>
  <Orig_str>APERTURA DELEGA</Orig_str>
  <Orig_str>AZZERAMENTO TOTALE DEI FILE PRESENTI 
PER l'INVIO AGENZIA ENTRATE</Orig_str>
    <ENG>Complete Delete of Files for send to Tax Agency</ENG>
  <Orig_str>Aggiorna</Orig_str>
    <ENG>Update</ENG>
  <Orig_str>Altri Intermediari</Orig_str>
    <ENG>Other Financial Companies</ENG>
  <Orig_str>Anagrafica Persone</Orig_str>
    <ENG>Identifications</ENG>
  <Orig_str>Anagrafica Rapporti</Orig_str>
    <ENG>Business Contracts</ENG>
  <Orig_str>Analitica</Orig_str>
    <ENG>Analytic Causal</ENG>
  <Orig_str>Anno</Orig_str>
    <ENG>Year</ENG>
  <Orig_str>Anno riferimento</Orig_str>
    <ENG>Reference Year</ENG>
  <Orig_str>Annotazioni</Orig_str>
    <ENG>Notes</ENG>
  <Orig_str>Annotazioni Varie</Orig_str>
  <Orig_str>Annotazioni varie</Orig_str>
  <Orig_str>Apertura</Orig_str>
    <ENG>Opening</ENG>
  <Orig_str>Apertura Spedita</Orig_str>
    <ENG>Sended Opening</ENG>
  <Orig_str>Apre Anagrafica</Orig_str>
    <ENG>Open Identification</ENG>
  <Orig_str>Archivio Unico Informatico</Orig_str>
    <ENG>DEFINITIVE</ENG>
  <Orig_str>Archivio di ricerca</Orig_str>
    <ENG>Query Table</ENG>
  <Orig_str>Area Geografica</Orig_str>
  <Orig_str>Area Geografica Operazione</Orig_str>
  <Orig_str>Aree Geografiche</Orig_str>
  <Orig_str>Attenzione !!!  L' Annullamento  HA UN SENSO SOLO SE
NESSUN FILE E' STATO INVIATO / GENERATO PER IL DIAGNOSTICO</Orig_str>
    <ENG>Be Careful! Do this only if you didn't send any file to Tax Agency</ENG>
  <Orig_str>Attenzione !!!  L' Annullamento Della Generazione 
HA UN SENSO SOLO SE IL FILE NON E' STATO INVIATO</Orig_str>
    <ENG>Be Careful! Do this only if you didn't send any file to Tax Agency</ENG>
  <Orig_str>Attiva Monitoraggio Applicazione</Orig_str>
    <ENG>Activate Log Creation</ENG>
  <Orig_str>Attivazione Log Procedura</Orig_str>
    <ENG>Activate Log Creation</ENG>
  <Orig_str>Attributi Selezionati</Orig_str>
    <ENG>Selected Attributes</ENG>
  <Orig_str>Aut. Competente</Orig_str>
    <ENG>Authority Issuing</ENG>
  <Orig_str>Autorità Competente</Orig_str>
    <ENG>Authority Issuing</ENG>
  <Orig_str>Autorità di rilascio</Orig_str>
    <ENG>Authority Issuing</ENG>
  <Orig_str>Autorità</Orig_str>
    <ENG>Authority</ENG>
  <Orig_str>Avere</Orig_str>
    <ENG>Credit</ENG>
  <Orig_str>Azienda</Orig_str>
    <ENG>Company</ENG>
  <Orig_str>B11 Lire/Euro Valuta</Orig_str>
  <Orig_str>B12. Codice Divisa</Orig_str>
  <Orig_str>B13. Segno monetario</Orig_str>
  <Orig_str>B14. Totale Lire / Euro * 100</Orig_str>
  <Orig_str>B15. Contanti Lire / Euro * 100</Orig_str>
  <Orig_str>Beneficiari</Orig_str>
    <ENG>Beneficiaries</ENG>
  <Orig_str>Beneficiario</Orig_str>
    <ENG>Beneficiary</ENG>
  <Orig_str>C.A.P.</Orig_str>
  <Orig_str>C11. Codice Cliente Intestatario</Orig_str>
  <Orig_str>C12. Sogg. Oper. Conto Terzi</Orig_str>
  <Orig_str>C13. Codice Beneficiario</Orig_str>
  <Orig_str>CAB</Orig_str>
    <ENG>CAB</ENG>
  <Orig_str>CAB Dipendenza</Orig_str>
    <ENG>Agency CAB</ENG>
  <Orig_str>CAB Intermediario C/Parte</Orig_str>
    <ENG>Other Financial Co. CAB</ENG>
  <Orig_str>CAP</Orig_str>
    <ENG>Zip Code</ENG>
  <Orig_str>CHIAVE</Orig_str>
    <ENG>KEY</ENG>
  <Orig_str>CHIUSURA DEL RAPPORTO</Orig_str>
    <ENG>CONTRACT END</ENG>
  <Orig_str>CHIUSURA DELEGA</Orig_str>
  <Orig_str>CODICE</Orig_str>
    <ENG>CODE</ENG>
  <Orig_str>COPIA OPERAZIONE MODIFICATA</Orig_str>
    <ENG>Modified Transaction Copy</ENG>
  <Orig_str>Cambio</Orig_str>
    <ENG>Exchange</ENG>
  <Orig_str>Cambio Intestatario</Orig_str>
    <ENG>Change Owner</ENG>
  <Orig_str>Cancella</Orig_str>
    <ENG>Delete</ENG>
  <Orig_str>Cancellazione Operazioni</Orig_str>
    <ENG>Delete Transactions</ENG>
  <Orig_str>Cancellazione Rapporti</Orig_str>
    <ENG>Delete Contracts</ENG>
  <Orig_str>Cap</Orig_str>
    <ENG>Zip Code</ENG>
  <Orig_str>Cau. Analitica</Orig_str>
    <ENG>Analytic Causal</ENG>
  <Orig_str>Cau. Sintetica</Orig_str>
    <ENG>Short Causal</ENG>
  <Orig_str>Causale</Orig_str>
    <ENG>Causal</ENG>
  <Orig_str>Causale Analitica</Orig_str>
    <ENG>Analytic Causal</ENG>
  <Orig_str>Causale Sintetica</Orig_str>
    <ENG>Short Causal</ENG>
  <Orig_str>Causali Analitiche</Orig_str>
    <ENG>Analytic Causals</ENG>
  <Orig_str>Causali Sintentiche</Orig_str>
    <ENG>Short Causals</ENG>
  <Orig_str>Chiave Riga</Orig_str>
  <Orig_str>Chiusura</Orig_str>
    <ENG>Close</ENG>
  <Orig_str>Citta</Orig_str>
    <ENG>City</ENG>
  <Orig_str>Città</Orig_str>
    <ENG>City</ENG>
  <Orig_str>Città Dipendenza</Orig_str>
    <ENG>Agency City</ENG>
  <Orig_str>Città Sede Legale</Orig_str>
    <ENG>Legal Address City</ENG>
  <Orig_str>Città di Nascita</Orig_str>
    <ENG>Birth Place:</ENG>
  <Orig_str>Cliente</Orig_str>
    <ENG>Customer</ENG>
  <Orig_str>Cliente Occasion.</Orig_str>
    <ENG>Customer</ENG>
  <Orig_str>Cliente Occasionale</Orig_str>
    <ENG>Customer</ENG>
  <Orig_str>Clienti</Orig_str>
    <ENG>Customers</ENG>
  <Orig_str>Cod. Fiscale</Orig_str>
    <ENG>Fiscal Code</ENG>
  <Orig_str>Codice</Orig_str>
    <ENG>Code</ENG>
  <Orig_str>Codice </Orig_str>
    <ENG>Code</ENG>
  <Orig_str>Codice Causale</Orig_str>
    <ENG>Causal Code</ENG>
  <Orig_str>Codice Città</Orig_str>
    <ENG>City Code</ENG>
  <Orig_str>Codice Cliente Occasionale</Orig_str>
    <ENG>Customer Code</ENG>
  <Orig_str>Codice Collegamento</Orig_str>
    <ENG>Link Code</ENG>
  <Orig_str>Codice Delegato</Orig_str>
    <ENG>Delegate Code</ENG>
  <Orig_str>Codice Dipendenza</Orig_str>
    <ENG>Agency Code</ENG>
  <Orig_str>Codice Divisa</Orig_str>
    <ENG>Currency Code</ENG>
  <Orig_str>Codice Fiscale</Orig_str>
    <ENG>Fiscal Code</ENG>
  <Orig_str>Codice Fiscale Errato</Orig_str>
    <ENG>Wrong Fiscal Code</ENG>
  <Orig_str>Codice Fiscale Estero</Orig_str>
    <ENG>Foreign Fiscal Code</ENG>
  <Orig_str>Codice Fiscale non attrib. dall'Agenzia delle Entrate </Orig_str>
    <ENG>Fiscal Code not from Tax Agency</ENG>
  <Orig_str>Codice Fiscale non attribuito dall'Agenzia delle Entrate (p.es. Sogg. Estero senza stabile organizz. o attività in Italia)</Orig_str>
    <ENG>Fiscal Code not from Tax Agency</ENG>
  <Orig_str>Codice Intermediario</Orig_str>
    <ENG>Company Code</ENG>
  <Orig_str>Codice Intermediario C/Parte</Orig_str>
    <ENG>Other Fin. Company Code</ENG>
  <Orig_str>Codice Intestatario</Orig_str>
    <ENG>Owner Code</ENG>
  <Orig_str>Codice Rapporto</Orig_str>
    <ENG>Business Contract Code</ENG>
  <Orig_str>Codice Soggetto</Orig_str>
    <ENG>Identification Code</ENG>
  <Orig_str>Codice Utente</Orig_str>
    <ENG>User Code</ENG>
  <Orig_str>Codice Utente CP</Orig_str>
    <ENG>User Code</ENG>
  <Orig_str>Codice Valuta</Orig_str>
    <ENG>Currency</ENG>
  <Orig_str>Cognome</Orig_str>
    <ENG>Surname</ENG>
  <Orig_str>Cointestato</Orig_str>
    <ENG>CO-Owner</ENG>
  <Orig_str>Collegamento</Orig_str>
    <ENG>Linkage</ENG>
  <Orig_str>Collegamento AOS</Orig_str>
    <ENG>AOS Linkage</ENG>
  <Orig_str>Collegamento Operazione Multiple</Orig_str>
    <ENG>Multiple Trasaction Link Code</ENG>
  <Orig_str>Collegamento con AOS</Orig_str>
    <ENG>AOS Linkage</ENG>
  <Orig_str>Collegata a</Orig_str>
    <ENG>Linked to</ENG>
  <Orig_str>Comune di Nascita</Orig_str>
    <ENG>Birth City</ENG>
  <Orig_str>Comune</Orig_str>
    <ENG>City</ENG>
  <Orig_str>Comuni</Orig_str>
    <ENG>Cities</ENG>
  <Orig_str>Con dettaglio operazioni</Orig_str>
    <ENG>With full operations</ENG>
  <Orig_str>Conferma Password</Orig_str>
    <ENG>Password Confirm</ENG>
  <Orig_str>Considerare solo i dati di Soggetti non ancora inviati</Orig_str>
    <ENG>Use only not already sended Subjects</ENG>
  <Orig_str>Contanti</Orig_str>
    <ENG>Cash</ENG>
  <Orig_str>Contanti (S/N)</Orig_str>
    <ENG>Cash</ENG>
  <Orig_str>Contatore</Orig_str>
    <ENG>Counter</ENG>
  <Orig_str>Controllo Data Registrazione</Orig_str>
    <ENG>Registration Date Check</ENG>
  <Orig_str>Controllo congruenza dati anagrafici persone fisiche e Codice Fiscale</Orig_str>
    <ENG>Check subject data with Fiscal Code</ENG>
  <Orig_str>Copia Operazione Modificata</Orig_str>
    <ENG>Modified Transaction Copy</ENG>
  <Orig_str>Crea Comunicazione Aperture</Orig_str>
    <ENG>Create Opening Communication</ENG>
  <Orig_str>Crea Comunicazione Aperture Rapporti</Orig_str>
    <ENG>Create Opening Communication</ENG>
  <Orig_str>Crea Comunicazione Chiusure</Orig_str>
    <ENG>Create Closing Communication</ENG>
  <Orig_str>Crea Comunicazione Chiusure Rapporti</Orig_str>
    <ENG>Create Closing Communication</ENG>
  <Orig_str>Crea Comunicazione Negativa</Orig_str>
    <ENG>Create Negative Communication</ENG>
  <Orig_str>Crea Modifiche / Annullamento</Orig_str>
    <ENG>Create Delete / Changes Communication</ENG>
  <Orig_str>Crea Modifiche / Annullamento Rapporti</Orig_str>
    <ENG>Create Delete / Changes Communication</ENG>
  <Orig_str>D11. Cliente Intestatario</Orig_str>
  <Orig_str>D13. Codice Paese Cliente</Orig_str>
  <Orig_str>D14a. CAB Comune Reside. Cliente</Orig_str>
  <Orig_str>D14b. Comune Residenza Cliente</Orig_str>
  <Orig_str>D14c. Provincia Residenza Cliente</Orig_str>
  <Orig_str>D15. Indirizzo Residenza Cliente</Orig_str>
  <Orig_str>D16. C.A.P. Cliente</Orig_str>
  <Orig_str>D17. Codice Fiscale Cliente</Orig_str>
  <Orig_str>D18. Data Nascita Cliente</Orig_str>
  <Orig_str>D19. Comune Nascita Cliente</Orig_str>
  <Orig_str>D21. Sottog. Att. Econ. Cliente</Orig_str>
  <Orig_str>D22. Ramo/Grp.. Att. Econ. Cliente</Orig_str>
  <Orig_str>D23. Settorizzaz. Sintetica Cliente</Orig_str>
  <Orig_str>D41. Tipo Documento Cliente</Orig_str>
  <Orig_str>D42. Numero Documento Cliente</Orig_str>
  <Orig_str>D43. Data Rilascio Documento Cliente</Orig_str>
  <Orig_str>D44. Autorità e Luogo Rilascio</Orig_str>
  <Orig_str>DATA</Orig_str>
    <ENG>Date</ENG>
  <Orig_str>DATA PRIMA OPERAZIONE DELL'ANNO</Orig_str>
    <ENG>First Annual Operation Date</ENG>
  <Orig_str>DATA e ORA</Orig_str>
    <ENG><![CDATA[DATE & TIME]]></ENG>
  <Orig_str>DATI ANAGRAFICI</Orig_str>
    <ENG>REGISTRY DATA</ENG>
  <Orig_str>DATI CENTRO SERVIZI</Orig_str>
    <ENG>SERVICES CENTER DATA</ENG>
  <Orig_str>DATI DALL'ELENCO SOGGETTI SEGNALATI</Orig_str>
  <Orig_str>DATI INVIO</Orig_str>
    <ENG>SENDING DATA</ENG>
  <Orig_str>DESCRIZIONE</Orig_str>
    <ENG>Description</ENG>
  <Orig_str>Da Cliente</Orig_str>
    <ENG>Start Customer</ENG>
  <Orig_str>Da Data Chiusura</Orig_str>
    <ENG>Start Closing Date</ENG>
  <Orig_str>Da Data Informazione</Orig_str>
    <ENG>From Information Date</ENG>
  <Orig_str>Da Data Modifica</Orig_str>
    <ENG>Start Modifing Date</ENG>
  <Orig_str>Da Data Operazione</Orig_str>
    <ENG>Start Transaction Date</ENG>
  <Orig_str>Da Data Variazione</Orig_str>
    <ENG>Start Modify Date</ENG>
  <Orig_str>Da Data</Orig_str>
    <ENG>Start Date</ENG>
  <Orig_str>Da Gruppo</Orig_str>
    <ENG>Start Branch</ENG>
  <Orig_str>Da Rapporto</Orig_str>
    <ENG>Start Business Contrat</ENG>
  <Orig_str>Da Sottogruppo</Orig_str>
    <ENG>Start Group</ENG>
  <Orig_str>Dare</Orig_str>
    <ENG>Debit</ENG>
  <Orig_str>Data</Orig_str>
    <ENG>Date</ENG>
  <Orig_str>Data Apertura</Orig_str>
    <ENG>Preceding Date</ENG>
  <Orig_str>Data Cancellazione / Variazione</Orig_str>
    <ENG>Delete / Modify Date</ENG>
  <Orig_str>Data Cancellazione</Orig_str>
    <ENG>Delete Date</ENG>
  <Orig_str>Data Chiusura Rapporto</Orig_str>
    <ENG>Stop Contract Date</ENG>
  <Orig_str>Data Chiusura</Orig_str>
    <ENG>Closing Date</ENG>
  <Orig_str>Data Fine</Orig_str>
    <ENG>End Date</ENG>
  <Orig_str>Data Fine Periodo</Orig_str>
    <ENG>End Date</ENG>
  <Orig_str>Data Fine Validità</Orig_str>
    <ENG>End Validity Date</ENG>
  <Orig_str>Data Generazione</Orig_str>
    <ENG>Generation Date</ENG>
  <Orig_str>Data Informazione</Orig_str>
    <ENG>Transaction Date</ENG>
  <Orig_str>Data Inizio</Orig_str>
    <ENG>Start Date</ENG>
  <Orig_str>Data Inizio Periodo</Orig_str>
    <ENG>Start Period Date</ENG>
  <Orig_str>Data Invio</Orig_str>
    <ENG>Send Date</ENG>
  <Orig_str>Data Massima Cancellazione Operazioni</Orig_str>
    <ENG>Max Date Transaction Deleting</ENG>
  <Orig_str>Data Massima Trasf a Storico</Orig_str>
    <ENG>Max Date Historical Transfer</ENG>
  <Orig_str>Data Modifica</Orig_str>
    <ENG>Modify Date</ENG>
  <Orig_str>Data Nascita</Orig_str>
    <ENG>Birth Date:</ENG>
  <Orig_str>Data Op.</Orig_str>
    <ENG>Trans. Date</ENG>
  <Orig_str>Data Oper.</Orig_str>
    <ENG>Trans. Date</ENG>
  <Orig_str>Data Operazione</Orig_str>
    <ENG>Transaction Date</ENG>
  <Orig_str>Data Operazione in carattere</Orig_str>
    <ENG>Literal Operation Date</ENG>
  <Orig_str>Data Passaggio EURO</Orig_str>
    <ENG>Using EURO Date</ENG>
  <Orig_str>Data Reg.</Orig_str>
    <ENG>Regist. Date</ENG>
  <Orig_str>Data Registrazione</Orig_str>
    <ENG>Registration Date</ENG>
  <Orig_str>Data Registrazione = Data Sistema</Orig_str>
    <ENG>Registration Date = System Date</ENG>
  <Orig_str>Data Registrazione non controllata</Orig_str>
    <ENG>Registration Date not Checked</ENG>
  <Orig_str>Data Rettifica</Orig_str>
    <ENG>Modify Date</ENG>
  <Orig_str>Data Rilascio</Orig_str>
    <ENG>Validity Start Date</ENG>
  <Orig_str>Data Rilascio Doc.</Orig_str>
    <ENG>Validity Start Date</ENG>
  <Orig_str>Data Spedizione Chiusura</Orig_str>
    <ENG>Closing Date</ENG>
  <Orig_str>Data Variazione</Orig_str>
    <ENG>Modify Date</ENG>
  <Orig_str>Data di Nascita</Orig_str>
    <ENG>Birth Date</ENG>
  <Orig_str>Data registrazione</Orig_str>
    <ENG>Registration Date</ENG>
  <Orig_str>Data rettifica apertura</Orig_str>
    <ENG>Opening Date</ENG>
  <Orig_str>Data rettifica chiusura</Orig_str>
    <ENG>Closing Date</ENG>
  <Orig_str>Dati Base</Orig_str>
    <ENG>Base Data</ENG>
  <Orig_str>Dati Generali</Orig_str>
    <ENG>General Data</ENG>
  <Orig_str>Dati Per Agenzia Entrate (Campi modificabili liberamente)</Orig_str>
    <ENG>Tax Agency Data (Free Data)</ENG>
  <Orig_str>Dati Soggetti/Rapporti Coinvolti nell'operazione</Orig_str>
    <ENG>Subjects/Contracts in Transaction Data</ENG>
  <Orig_str>Dati eventuale Intermediario ControParte</Orig_str>
    <ENG>Other Financial Company Data</ENG>
  <Orig_str>Definitivo</Orig_str>
    <ENG>Final</ENG>
  <Orig_str>Delega Conto Terzi</Orig_str>
  <Orig_str>Delegato</Orig_str>
    <ENG>Delegate</ENG>
  <Orig_str>Deleghe su Rapporti</Orig_str>
    <ENG>Contracts Delegations</ENG>
  <Orig_str>Deleghe sui rapporti</Orig_str>
    <ENG>Contracts Delegations</ENG>
  <Orig_str>Denominazione</Orig_str>
    <ENG>Denomination</ENG>
  <Orig_str>Denominazione Intermediario C/Parte</Orig_str>
    <ENG>Other Financial Company Name</ENG>
  <Orig_str>Denominazioni Simili</Orig_str>
    <ENG>Similar Denomination</ENG>
  <Orig_str>Desc Banca Semplificata</Orig_str>
    <ENG>Simply Bank Descr.</ENG>
  <Orig_str>Desc. Legame</Orig_str>
    <ENG>Link Desc.</ENG>
  <Orig_str>Descrizione</Orig_str>
    <ENG>Description</ENG>
  <Orig_str>Descrizione 2</Orig_str>
    <ENG>2nd Description</ENG>
  <Orig_str>Descrizione Analitica</Orig_str>
    <ENG>Analitic Description</ENG>
  <Orig_str>Descrizione Sintetica</Orig_str>
    <ENG>Sintetic Description</ENG>
  <Orig_str>Descrizione estesa</Orig_str>
    <ENG>Complete Description</ENG>
  <Orig_str>Destinazione</Orig_str>
    <ENG>Destination</ENG>
  <Orig_str>Dettaglio Operazione</Orig_str>
    <ENG>Transaction Detail</ENG>
  <Orig_str>Dipen.</Orig_str>
    <ENG>Agency</ENG>
  <Orig_str>Dipendenza</Orig_str>
    <ENG>Agency</ENG>
  <Orig_str>Dipendenze</Orig_str>
    <ENG>Agencies</ENG>
  <Orig_str>Divisa</Orig_str>
    <ENG>Currency</ENG>
  <Orig_str>Domicilio</Orig_str>
    <ENG>Address</ENG>
  <Orig_str>E11. Sogg. Operante Conto Terzi</Orig_str>
  <Orig_str>E13. Codice Paese Sog. Oper.</Orig_str>
  <Orig_str>E14a. CAB Comune Res. Sog.Oper.</Orig_str>
  <Orig_str>E14b. Comune Resid. Sog. Oper.</Orig_str>
  <Orig_str>E14c. Provincia Residenza Sog. Oper.</Orig_str>
  <Orig_str>E15. Indirizzo Resid. Sog. Oper.</Orig_str>
  <Orig_str>E16. C.A.P. Sog. Oper.</Orig_str>
  <Orig_str>E17. Codice Fiscale Sog. Oper.</Orig_str>
  <Orig_str>E18. Data Nascita Sog. Oper.</Orig_str>
  <Orig_str>E19. Comune Nascita Sog. Oper.</Orig_str>
  <Orig_str>E41. Tipo Documento Sog. Oper.</Orig_str>
  <Orig_str>E42. N° Documento Sog. Oper.</Orig_str>
  <Orig_str>E43. Data Rilascio Doc. Sog. Oper.</Orig_str>
  <Orig_str>E44. Autorità e Luogo Rilascio</Orig_str>
  <Orig_str>EMail</Orig_str>
  <Orig_str>ERRORE</Orig_str>
    <ENG>ERROR</ENG>
  <Orig_str>ESITO DI RICERCA TRA NOMI SEGNALATI</Orig_str>
  <Orig_str>ESITO DI RICERCA TRA SOGGETTI SEGNALATI</Orig_str>
  <Orig_str>Effettua la ricerca</Orig_str>
  <Orig_str>Elenco Titolo</Orig_str>
    <ENG>List Title</ENG>
  <Orig_str>Elenco Utenti</Orig_str>
    <ENG>User List</ENG>
  <Orig_str>Eliminazione Rettifica</Orig_str>
    <ENG>Delete Changes</ENG>
  <Orig_str>Eliminazione comunicazione apertura</Orig_str>
    <ENG>Delete Opening Communication</ENG>
  <Orig_str>Eliminazione comunicazione chiusura</Orig_str>
    <ENG>Delete Closing Communication</ENG>
  <Orig_str>Esegui</Orig_str>
    <ENG>Exec</ENG>
  <Orig_str>Estrazione Rapporti per primo invio</Orig_str>
    <ENG>First Sending Data Extraction</ENG>
  <Orig_str>Estrazione Rapporti per secondo invio</Orig_str>
    <ENG>Second Sending Data Extraction</ENG>
  <Orig_str>Estrazione UIC DIANA</Orig_str>
    <ENG>Extract DIANA UIC</ENG>
  <Orig_str>Estrazione mensile Deleghe/Operazioni Extraconto per Agenzia delle Entrate</Orig_str>
  <Orig_str>Estrazione mensile Rapporti per Agenzia delle Entrate</Orig_str>
    <ENG>Periodical Sending Data Extraction</ENG>
  <Orig_str>Euro</Orig_str>
    <ENG>Euro</ENG>
  <Orig_str>Euro Transitorio</Orig_str>
    <ENG>Euro</ENG>
  <Orig_str>Button</Orig_str>
  <Orig_str>LinkPC</Orig_str>
  <Orig_str>F14a. CAB Comune Res. Benefic.</Orig_str>
  <Orig_str>F14b. Comune Resid. Beneficiario</Orig_str>
  <Orig_str>F14c. Provincia Residenza Beneficiario</Orig_str>
  <Orig_str>F15. Indirizzo Resid. Beneficiario</Orig_str>
  <Orig_str>F16. C.A.P. Beneficiario</Orig_str>
  <Orig_str>F17. Codice Fiscale Beneficiario</Orig_str>
  <Orig_str>FRAZIONATE RAPPORTI</Orig_str>
    <ENG>TRANSACTIONS UNDER 12500</ENG>
  <Orig_str>Femmina</Orig_str>
    <ENG>Female</ENG>
  <Orig_str>Femminile</Orig_str>
    <ENG>Female</ENG>
  <Orig_str>File Generati</Orig_str>
    <ENG>Generated Files</ENG>
  <Orig_str>File spedizione Chiusura</Orig_str>
    <ENG>Closing Files</ENG>
  <Orig_str>Fine</Orig_str>
    <ENG>End</ENG>
  <Orig_str>Fine Validità</Orig_str>
    <ENG>End Validity</ENG>
  <Orig_str>Frazionarie</Orig_str>
    <ENG>Under 15000</ENG>
  <Orig_str>Frazionata (S/N)</Orig_str>
    <ENG>Transation Under 15000</ENG>
  <Orig_str>Frazionata Trasferita</Orig_str>
    <ENG>Transaction Transfered</ENG>
  <Orig_str>Frazionate</Orig_str>
    <ENG>Transcations under 15000</ENG>
  <Orig_str>Gruppi</Orig_str>
    <ENG>Groups</ENG>
  <Orig_str>Gruppo</Orig_str>
    <ENG>Group</ENG>
  <Orig_str>Gruppo 1</Orig_str>
    <ENG>Group 1</ENG>
  <Orig_str>Gruppo 2</Orig_str>
    <ENG>Group 2</ENG>
  <Orig_str>Gruppo 3</Orig_str>
    <ENG>Group 3</ENG>
  <Orig_str>Gruppo 4</Orig_str>
    <ENG>Group 4</ENG>
  <Orig_str>Gruppo 5</Orig_str>
    <ENG>Group 5</ENG>
  <Orig_str>ID</Orig_str>
  <Orig_str>ID BASE</Orig_str>
    <ENG>Basic ID</ENG>
  <Orig_str>ID BASE Causale Analitica</Orig_str>
    <ENG>ID Analytic Causal</ENG>
  <Orig_str>ID RIferimento</Orig_str>
  <Orig_str>ID Registrazione</Orig_str>
    <ENG>Registration ID</ENG>
  <Orig_str>IDBASE</Orig_str>
  <Orig_str>INFORMAZIONI</Orig_str>
    <ENG>INFORMATIONS</ENG>
  <Orig_str>INFORMAZIONI SUI RAPPORTI</Orig_str>
    <ENG>CONTRACTS INFORMATIONS</ENG>
  <Orig_str>INTERVALLO DATE OPERAZIONE</Orig_str>
    <ENG>TRANSACTIONS DATE PERIOD</ENG>
  <Orig_str>INTESTATARI RAPPORTI</Orig_str>
    <ENG>CONTRACTS OWNERS</ENG>
  <Orig_str>ISO 2</Orig_str>
  <Orig_str>ISO</Orig_str>
  <Orig_str>Idbase</Orig_str>
  <Orig_str>Idbase di Operazbo</Orig_str>
  <Orig_str>Identificativo Registrazione</Orig_str>
    <ENG>Registration Identity</ENG>
  <Orig_str>Il rapporto esiste già nell'anagrafica effettiva</Orig_str>
    <ENG>Business Contract already existing !</ENG>
  <Orig_str>Impedisce registrazioni se DataReg. # Data Sistema</Orig_str>
    <ENG><![CDATA[Stop registration if Registration Date <> System Date]]></ENG>
  <Orig_str><![CDATA[Impedisce registrazioni se DataReg. < Data Sistema]]></Orig_str>
    <ENG><![CDATA[Stop registration if Registration Date < System Date]]></ENG>
  <Orig_str>Importazione da file esterno</Orig_str>
    <ENG>Import from External File</ENG>
  <Orig_str>Importo</Orig_str>
    <ENG>Amount</ENG>
  <Orig_str>Impossibile aggiungere nuove operazioni in archivio storico</Orig_str>
    <ENG>Impossible to add a transaction in Historical Archive</ENG>
  <Orig_str>Impossibile cancellare operazioni in archivio storico</Orig_str>
    <ENG>Existing records relative to this business contract</ENG>
  <Orig_str><![CDATA[<]]></Orig_str>
  <Orig_str>Impossibile selezionare un periodo precedente al 30/04/2007</Orig_str>
    <ENG>Impossible select period before 04/30/2007</ENG>
  <Orig_str>Impossibile selezionare un periodo precedente al 30/06/2008</Orig_str>
    <ENG>Impossible select period before 06/30/2008</ENG>
  <Orig_str>Impossibile utilizzare una operazione non relativa al rapporto</Orig_str>
    <ENG>Impossible to use a transaction not belonging to contract</ENG>
  <Orig_str>Indirizzo</Orig_str>
    <ENG>Address</ENG>
  <Orig_str>Informazione Rapporto</Orig_str>
    <ENG>Contract Information</ENG>
  <Orig_str>Informazioni sui rapporti</Orig_str>
    <ENG>Contract Information</ENG>
  <Orig_str>Inizio</Orig_str>
    <ENG>Start</ENG>
  <Orig_str>Inserire P per Intestatario o D per Delegato</Orig_str>
    <ENG>P for Owner or D for Delegate</ENG>
  <Orig_str>Intermediari</Orig_str>
    <ENG>Companies</ENG>
  <Orig_str>Intermediari ControParte</Orig_str>
    <ENG>Other Financial Companies</ENG>
  <Orig_str>Intermediario</Orig_str>
    <ENG>Company</ENG>
  <Orig_str>Intermediario C/Parte</Orig_str>
    <ENG>Other Financial Company</ENG>
  <Orig_str>Intermediario Controparte</Orig_str>
    <ENG>Other Financial Company</ENG>
  <Orig_str>Intestatari</Orig_str>
    <ENG>Owners</ENG>
  <Orig_str>Intestatari/Delegati</Orig_str>
    <ENG>Owners/Delegates</ENG>
  <Orig_str>Intestatario</Orig_str>
    <ENG>Owner</ENG>
  <Orig_str>Intestatario (Non Intermediario)</Orig_str>
    <ENG>Owner (Not Company)</ENG>
  <Orig_str>Intestatario / Delegato</Orig_str>
    <ENG>Owner / Delegate</ENG>
  <Orig_str>Intestazione</Orig_str>
    <ENG>Owner</ENG>
  <Orig_str>LISTA RAPPORTI PER AGENZIA ENTRATE</Orig_str>
    <ENG>Tax Agency Contracts List</ENG>
  <Orig_str>La data di fine deve essere superiore a quella di inizio e la differenza deve essere di almeno 7 giorni</Orig_str>
    <ENG><![CDATA[End Period Date must be < than Start Period Date and Differece must be at least 7 days]]></ENG>
  <Orig_str>La data di fine periodo deve essere minore di quella di inizio periodo !</Orig_str>
    <ENG><![CDATA[End Period Date must be > than Start Period Date]]></ENG>
  <Orig_str>La data di inizio periodo deve essere minore di quella fine periodo</Orig_str>
    <ENG><![CDATA[End Period Date must be > than Start Period Date]]></ENG>
  <Orig_str>La data fine periodo deve essere superiore a quella di inizio periodo</Orig_str>
    <ENG><![CDATA[End Period Date must be > than Start Period Date]]></ENG>
  <Orig_str>La data fine periodo deve essere superiore a quella di inizo periodo</Orig_str>
    <ENG><![CDATA[End Period Date must be > than Start Period Date]]></ENG>
  <Orig_str>La differenza di date non deve superare i 30 gg</Orig_str>
    <ENG><![CDATA[Differcence between start and end date must be > than 30 days]]></ENG>
  <Orig_str>La password deve contenere almeno 8 caratteri</Orig_str>
    <ENG>Passowrd length at lest 8 characters</ENG>
  <Orig_str>La ricerca di soggetto segnalato, in base ai criteri sotto esposti, ha dato esito negativo</Orig_str>
  <Orig_str>La vecchia password è errata !</Orig_str>
    <ENG>Wrong old password !</ENG>
  <Orig_str>Legame</Orig_str>
    <ENG>Link</ENG>
  <Orig_str>Lira</Orig_str>
    <ENG>Lire</ENG>
  <Orig_str>Lire</Orig_str>
    <ENG>Lire</ENG>
  <Orig_str>Lire Euro Valuta</Orig_str>
    <ENG>Lire Euro Currency</ENG>
  <Orig_str>Località</Orig_str>
    <ENG>City Name</ENG>
  <Orig_str>Login</Orig_str>
    <ENG>OK</ENG>
  <Orig_str>Luogo di Nascita</Orig_str>
    <ENG>Birth Place</ENG>
  <Orig_str>MODIFICA DATI PER SCARTO RAPPORTO DA ENTRATEL ?</Orig_str>
    <ENG>Change Data for wrong communication ?</ENG>
  <Orig_str>MOTIVO</Orig_str>
    <ENG>REASON</ENG>
  <Orig_str>Maschile</Orig_str>
    <ENG>Male</ENG>
  <Orig_str>Maschio</Orig_str>
    <ENG>Male</ENG>
  <Orig_str>Modalità Svolgimento</Orig_str>
    <ENG>Progress Type</ENG>
  <Orig_str>Modifica</Orig_str>
    <ENG>Modify</ENG>
  <Orig_str>Modifica Data Chiusura</Orig_str>
    <ENG>Modify Stop Date</ENG>
  <Orig_str>Modifica Data Iniziale e/o Intestatario</Orig_str>
    <ENG>Modify Starting Date or Owner</ENG>
  <Orig_str>Modifica Dati Base Rapporto</Orig_str>
    <ENG>Modify Contract Base Data </ENG>
  <Orig_str>Modifica Dati Intestatario (Persona Fisica)</Orig_str>
    <ENG>Modify Owner Data (Phisical)</ENG>
  <Orig_str>Modifica Dati Intestatario (Persona Giuridica)</Orig_str>
    <ENG>Modify Owner Data (Juridical)</ENG>
  <Orig_str>Modifica dati Intestatario</Orig_str>
    <ENG>Modify Owner Data</ENG>
  <Orig_str>Modifica dati per scarto da Entratel</Orig_str>
    <ENG>Modify Data by Entratel </ENG>
  <Orig_str>Monitoraggio Applicazione</Orig_str>
    <ENG>Log Procedure</ENG>
  <Orig_str>Multipla</Orig_str>
    <ENG>Multiple</ENG>
  <Orig_str>N + F</Orig_str>
  <Orig_str>N.B.: I NOMI DEI FILE CREATI NON DEVONO 
ESSERE MODIFICATI PER NESSUN MOTIVO !!!</Orig_str>
    <ENG>N.B.: FILE NAMES MUST NOT BE MODIFIED</ENG>
  <Orig_str>Natura Rapporto</Orig_str>
  <Orig_str>Natura</Orig_str>
    <ENG>Nature</ENG>
  <Orig_str>Nazione (UIC)</Orig_str>
    <ENG>Country (UIC)</ENG>
  <Orig_str>No codice fiscale (Non assegnato agenzia entrate)</Orig_str>
    <ENG>No Fiscal Code (Not generated by Tax Agency)</ENG>
  <Orig_str>Nome</Orig_str>
    <ENG>Name</ENG>
  <Orig_str>Nome File Generato</Orig_str>
    <ENG>Generated File</ENG>
  <Orig_str>Nome File Spedizione</Orig_str>
    <ENG>Sending File Name</ENG>
  <Orig_str>Nome Vecchio File</Orig_str>
    <ENG>Old File Name</ENG>
  <Orig_str>Nome del file dati da importare</Orig_str>
    <ENG>Import File Path</ENG>
  <Orig_str>Nome del file generato</Orig_str>
    <ENG>Generated File</ENG>
  <Orig_str>Nome file spedizione chiusura</Orig_str>
    <ENG>Sending Close File Name</ENG>
  <Orig_str>Nominativo</Orig_str>
    <ENG>Name</ENG>
  <Orig_str>Non Cointestato</Orig_str>
    <ENG>Not Co-Headed</ENG>
  <Orig_str>Non inviare Agenzia Entrate</Orig_str>
    <ENG>Not to send to Tax Agency</ENG>
  <Orig_str>Non inviare agenzia Entrate</Orig_str>
    <ENG>Not to send to tax Agency</ENG>
  <Orig_str>Non inviare agenzia entrate</Orig_str>
    <ENG>Not to send to tax Agency</ENG>
  <Orig_str>Numero Doc.</Orig_str>
    <ENG>Document Number</ENG>
  <Orig_str>Numero Documento</Orig_str>
    <ENG>Document Number</ENG>
  <Orig_str>Numero Invio</Orig_str>
    <ENG>Sending Number</ENG>
  <Orig_str>Numero Progressivo</Orig_str>
    <ENG>ID Number</ENG>
  <Orig_str>Numero Progressivo Relativo Chiusura</Orig_str>
    <ENG>Prog. Closing Number </ENG>
  <Orig_str>Numero Progressivo relativo</Orig_str>
    <ENG>Prog. Opening Number</ENG>
  <Orig_str>Nuova Apertura</Orig_str>
    <ENG>New Close Date</ENG>
  <Orig_str>Nuova Chiusura</Orig_str>
    <ENG>New Close Date</ENG>
  <Orig_str>Nuova Informazione</Orig_str>
    <ENG>New Information</ENG>
  <Orig_str>Nuova Password</Orig_str>
    <ENG>New Password</ENG>
  <Orig_str>Nuovo Intestatario</Orig_str>
    <ENG>New Owner</ENG>
  <Orig_str>Nuovo Tipologia</Orig_str>
    <ENG>New Type</ENG>
  <Orig_str>N° Documento</Orig_str>
    <ENG>Document Number</ENG>
  <Orig_str>N° Fine</Orig_str>
    <ENG>End Number</ENG>
  <Orig_str>N° Informazione</Orig_str>
    <ENG>Transaction Number:</ENG>
  <Orig_str>N° Inizio</Orig_str>
    <ENG>Start Number</ENG>
  <Orig_str>N° Operazione</Orig_str>
    <ENG>Transaction Number</ENG>
  <Orig_str>N° Prog</Orig_str>
    <ENG>ID  Number</ENG>
  <Orig_str>N° Progr.</Orig_str>
    <ENG>ID Number</ENG>
  <Orig_str>N° Progressivo</Orig_str>
    <ENG>ID Number</ENG>
  <Orig_str>N° Registrazione</Orig_str>
    <ENG>Registration Number</ENG>
  <Orig_str>N° Riga</Orig_str>
    <ENG>Row N°</ENG>
  <Orig_str>N°Documento</Orig_str>
    <ENG>Document Num.</ENG>
  <Orig_str>N°Progressivo</Orig_str>
    <ENG>ID Number</ENG>
  <Orig_str>OPERAZIONE</Orig_str>
    <ENG>TRANSACTION</ENG>
  <Orig_str>OPERAZIONE CANCELLATA</Orig_str>
    <ENG>DELETED TRANSACTION</ENG>
  <Orig_str>OPERAZIONI RAPPORTI</Orig_str>
    <ENG>CONTRACTS TRANSACTIONS</ENG>
  <Orig_str>Op. Collegata</Orig_str>
    <ENG>Liked Trans.</ENG>
  <Orig_str>Operatore</Orig_str>
    <ENG>Operator</ENG>
  <Orig_str>Operatore di confronto</Orig_str>
  <Orig_str>Operazione</Orig_str>
    <ENG>Transaction</ENG>
  <Orig_str>Operazione Cancellata</Orig_str>
    <ENG>Deleted Transaction</ENG>
  <Orig_str>Operazione Modificata</Orig_str>
    <ENG>Modified Transaction</ENG>
  <Orig_str>Operazione attiva</Orig_str>
    <ENG>Transaction</ENG>
  <Orig_str>Operazione/Rapporto</Orig_str>
    <ENG>Transaction / Contract</ENG>
  <Orig_str>Operazioni</Orig_str>
    <ENG>Transactions</ENG>
  <Orig_str>Operazioni Attive</Orig_str>
    <ENG>Active Transactions</ENG>
  <Orig_str>Operazioni Cancellate</Orig_str>
    <ENG>Deleted Transactions</ENG>
  <Orig_str>Operazioni ExtraConto</Orig_str>
    <ENG>Extra Account Operations</ENG>
  <Orig_str>Operazioni Modificate</Orig_str>
    <ENG>Modified Transactions</ENG>
  <Orig_str>Operazioni Ordinarie</Orig_str>
    <ENG>Transactions</ENG>
  <Orig_str>P. IVA</Orig_str>
    <ENG>VAT Code</ENG>
  <Orig_str>P.IVA</Orig_str>
    <ENG>VAT Code</ENG>
  <Orig_str>PERSONE / SOCIETA'  / FORNITORI</Orig_str>
    <ENG>SUBJECTS</ENG>
  <Orig_str>PROV.</Orig_str>
    <ENG>County</ENG>
  <Orig_str>PROVVISORIE</Orig_str>
    <ENG>PROVISIONALS</ENG>
  <Orig_str>Partita IVA</Orig_str>
    <ENG>VAT Code</ENG>
  <Orig_str>Passaggio EURO</Orig_str>
    <ENG>Using EURO Date</ENG>
  <Orig_str>Passato EURO</Orig_str>
    <ENG>Using EURO</ENG>
  <Orig_str>Passato a Euro</Orig_str>
    <ENG>Using EURO</ENG>
  <Orig_str>Path Applicazione</Orig_str>
    <ENG>Application path</ENG>
  <Orig_str>Path applicazione</Orig_str>
    <ENG>Application path</ENG>
  <Orig_str>Per Annullare l' estrazione
OCCORRE SAPERE IL NOME DEL FILE GENERATO</Orig_str>
    <ENG>To Delete the import is necessary
to know the generated file name</ENG>
  <Orig_str>Periodo 01/01/2005 - 31/12/2006 da inviare entro il 30/04/2007</Orig_str>
    <ENG>Period 01/01/2005 - 31/12/2006 to send within 30/04/2007</ENG>
  <Orig_str>Periodo 01/01/2007 - 30/04/2007 da inviare entro il 31/05/2007</Orig_str>
    <ENG>Periodo 01/01/2007 - 30/04/2007 to send within 31/05/2007</ENG>
  <Orig_str>Periodo mensile da inviare entro il mese successivo</Orig_str>
    <ENG>Monthly period to send in the next month</ENG>
  <Orig_str>Persona Fisica</Orig_str>
    <ENG>Phisical Subject</ENG>
  <Orig_str>Persona Giuridica</Orig_str>
    <ENG>Society</ENG>
  <Orig_str>Persone / Società / Legali Rappresentanti</Orig_str>
    <ENG>Subjects</ENG>
  <Orig_str>Pr.</Orig_str>
    <ENG>Dist.</ENG>
  <Orig_str>Precedente file spedizione chiusura</Orig_str>
  <Orig_str>Precedente progressivo spedizione</Orig_str>
  <Orig_str>Precedente riferimento chiusura</Orig_str>
  <Orig_str>Prefisso Telefonico</Orig_str>
    <ENG>Dialing Code</ENG>
  <Orig_str>Premere il bottone per caricare i soggetti il cui rapporto non è ancora chiuso</Orig_str>
  <Orig_str>Preparazione disco per cancellazione Società Elenco Intermediari U.I.C.</Orig_str>
  <Orig_str>Prima Estrazione dei Rapporti per Agenzia Entrate
Periodo 01/01/05 - 31/12/2006 da inviare entro il 30/04/2007</Orig_str>
  <Orig_str>Prima Estrazione delle Deleghe/Operazioni per Agenzia Entrate
Periodo 01/01/2005 - 31/12/2007 da inviare entro il 30/06/2008</Orig_str>
  <Orig_str>Primo Invio: Periodo 01/01/2005 - 31/12/2006 da inviare entro il 30/04/2007</Orig_str>
  <Orig_str>Profilo</Orig_str>
    <ENG>User Type</ENG>
  <Orig_str>Progressivo</Orig_str>
    <ENG>ID Number</ENG>
  <Orig_str>Progressivo Atuale</Orig_str>
    <ENG>Actual ID</ENG>
  <Orig_str>Prov.</Orig_str>
    <ENG>District</ENG>
  <Orig_str>Provincia</Orig_str>
    <ENG>District</ENG>
  <Orig_str>Provincia (EE se estero)</Orig_str>
    <ENG>Disctrict (EE for foreign)</ENG>
  <Orig_str>Provincia Dipendenza</Orig_str>
    <ENG>Agency District</ENG>
  <Orig_str>Provincia Intermediario C/Parte</Orig_str>
    <ENG>Other Fin. Co. District</ENG>
  <Orig_str>Provissorio</Orig_str>
    <ENG>Provisional</ENG>
  <Orig_str>Prv.</Orig_str>
    <ENG>District</ENG>
  <Orig_str>Questa procedura estrae i dati da A.U.I. e li predispone per essere
inviati all'Agenzia delle Entrate
Naturalmente una volta estratti i dati possono essere modificati
nella voce di MENU 7.2</Orig_str>
  <Orig_str>Questa procedura estrae i dati da A.U.I. e li predispone per essere
inviati all'Agenzia delle Entrate
Naturalmente una volta estratti i dati possono essere modificati
nella voce di MENU 8.2 / 8.3</Orig_str>
  <Orig_str>RAPPORTO</Orig_str>
    <ENG>CONTRACT</ENG>
  <Orig_str>Ragione Sociale</Orig_str>
    <ENG>Company Name</ENG>
  <Orig_str>Ragionevolezza</Orig_str>
  <Orig_str>Ragionevolezza Operazione</Orig_str>
  <Orig_str>Ramo Gruppo Att. Ec.</Orig_str>
    <ENG>Economic Branch</ENG>
  <Orig_str>Ramo/Gruppo Att. Econ.</Orig_str>
    <ENG>Economic Branch</ENG>
  <Orig_str>Ramo/Gruppo Attività Economica</Orig_str>
    <ENG>Economic Branch</ENG>
  <Orig_str>Rapporti Continuativi</Orig_str>
    <ENG>Business Contracts</ENG>
  <Orig_str>Rapporti Continuativi in essere</Orig_str>
    <ENG>Provisional Business Contracts</ENG>
  <Orig_str>Rapporti Provvisori</Orig_str>
    <ENG>Business Contracts</ENG>
  <Orig_str>Rapporti in essere</Orig_str>
    <ENG>Business Contracts</ENG>
  <Orig_str>Rapporto</Orig_str>
    <ENG>Business Contract</ENG>
  <Orig_str>Rapporto (Copia della testata)</Orig_str>
    <ENG>Contract</ENG>
  <Orig_str>Rapporto / Cliente Occ.</Orig_str>
    <ENG>Contract / Customer</ENG>
  <Orig_str>Rapporto / Cliente Occas.</Orig_str>
    <ENG>Contract / Customer</ENG>
  <Orig_str>Rapporto Beneficiario</Orig_str>
    <ENG>Beneficiary Contract</ENG>
  <Orig_str>Rapporto Collegato</Orig_str>
    <ENG>Linked Contract</ENG>
  <Orig_str>Reinserire la password</Orig_str>
    <ENG>Re-Type Password</ENG>
  <Orig_str>Responsabile Inserimento</Orig_str>
  <Orig_str>Rettifica di Comunicazione accettata da Entratel ma che si desidera cambiare</Orig_str>
  <Orig_str>Ricerca denominazioni simili</Orig_str>
  <Orig_str>Richieste</Orig_str>
    <ENG>Requests</ENG>
  <Orig_str>Riferimento Anagrafico</Orig_str>
  <Orig_str>Riferimento File</Orig_str>
  <Orig_str>Riferimento Spedizione Apertura</Orig_str>
  <Orig_str>Riferimento Spedizione</Orig_str>
  <Orig_str>Riferimento file spedizione</Orig_str>
  <Orig_str>Riferimento file vecchia spedizione</Orig_str>
  <Orig_str>Riferimento spedizione chiusura</Orig_str>
  <Orig_str>Rilascio Doc.</Orig_str>
    <ENG>Start Validity Date</ENG>
  <Orig_str>STAMPA ANOMALIE RISCONTRATE</Orig_str>
  <Orig_str>Sblocco controllo</Orig_str>
  <Orig_str>Seconda Estrazione dei Rapporti per Agenzia Entrate
Periodo 01/01/07 - 30/04/2007 da inviare entro il 31/05/2007</Orig_str>
  <Orig_str>Seconda Estrazione delle Deleghe/Operazioni per Agenzia Entrate
Periodo 01/01/2008 - 30/06/2008 da inviare entro il 31/07/2008</Orig_str>
  <Orig_str>Secondo Invio: Periodo 01/01/2007 - 30/04/2007 da inviare entro il 31/05/2007</Orig_str>
  <Orig_str><![CDATA[Segnala se DataReg. < Data Sistema]]></Orig_str>
    <ENG><![CDATA[Alert if Registration Date < System Date]]></ENG>
  <Orig_str>Segno</Orig_str>
    <ENG>Sign</ENG>
  <Orig_str>Seleziona</Orig_str>
    <ENG>Select</ENG>
  <Orig_str>Selezione Rettifiche / Cancellazioni</Orig_str>
  <Orig_str>Servizio</Orig_str>
  <Orig_str>Sesso</Orig_str>
    <ENG>Sex</ENG>
  <Orig_str>Setto Sintetica UIC</Orig_str>
    <ENG>UIC Sector</ENG>
  <Orig_str>Settorizzazione Sintetica</Orig_str>
    <ENG>UIC Sector</ENG>
  <Orig_str>Settorizzazione UIC</Orig_str>
    <ENG>UIC Sector</ENG>
  <Orig_str>Si</Orig_str>
    <ENG>Yes</ENG>
  <Orig_str>Sigla</Orig_str>
    <ENG>Mark</ENG>
  <Orig_str>Simbolo</Orig_str>
    <ENG>Symbol</ENG>
  <Orig_str>Sintetica</Orig_str>
    <ENG>Short Causal</ENG>
  <Orig_str>Sog. Op. Conto Terzi</Orig_str>
    <ENG>Other Operator</ENG>
  <Orig_str>Sogg. Op. C. Terzi</Orig_str>
    <ENG>Other Operator</ENG>
  <Orig_str>Sogg. Op. Conto Terzi</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>Sogg. Operante</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>Soggetti</Orig_str>
    <ENG>Subjects</ENG>
  <Orig_str>Soggetti Agenti per Conto / Dati Agenzia Entrate</Orig_str>
    <ENG>Other Subjects / Tax Agency</ENG>
  <Orig_str>Soggetti Agenti per Conto Inform.</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>Soggetti Operanti</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>Soggetti Registrati</Orig_str>
    <ENG>Registered Subjects</ENG>
  <Orig_str>Soggetti conto informazioni</Orig_str>
    <ENG>Other Operators</ENG>
  <Orig_str>Soggetto Operante Conto Terzi</Orig_str>
    <ENG>Other Operator</ENG>
  <Orig_str>Soggetto Operante Delegato</Orig_str>
    <ENG>Other Operator</ENG>
  <Orig_str>Solo Persone Fisiche</Orig_str>
    <ENG>Only Persons</ENG>
  <Orig_str>Solo per Persone Fisiche</Orig_str>
    <ENG>Only Persons</ENG>
  <Orig_str>Solo persone fisiche</Orig_str>
    <ENG>Only Persons</ENG>
  <Orig_str>Sono selezionabili al massimo 15 attributi</Orig_str>
    <ENG>Max 15 attributes</ENG>
  <Orig_str>SottoGrup. Att. Economica</Orig_str>
    <ENG>Economic Group</ENG>
  <Orig_str>Sottogruppi</Orig_str>
    <ENG>SubGroups</ENG>
  <Orig_str>Sottogruppi Att. Economiche</Orig_str>
    <ENG>Economic Group</ENG>
  <Orig_str>Sottogruppi Attività Economica</Orig_str>
    <ENG>Economic Group</ENG>
  <Orig_str>Sottogruppo</Orig_str>
    <ENG>Subgroup</ENG>
  <Orig_str>Sottogruppo 10</Orig_str>
    <ENG>Subgroup 10</ENG>
  <Orig_str>Sottogruppo 11</Orig_str>
    <ENG>Subgroup 11</ENG>
  <Orig_str>Sottogruppo 12</Orig_str>
    <ENG>Subgroup 12</ENG>
  <Orig_str>Sottogruppo 1</Orig_str>
    <ENG>Subgroup 1</ENG>
  <Orig_str>Sottogruppo 2</Orig_str>
    <ENG>Subgroup 2</ENG>
  <Orig_str>Sottogruppo 3</Orig_str>
    <ENG>Subgroup 3</ENG>
  <Orig_str>Sottogruppo 4</Orig_str>
    <ENG>Subgroup 4</ENG>
  <Orig_str>Sottogruppo 5</Orig_str>
    <ENG>Subgroup 5</ENG>
  <Orig_str>Sottogruppo 6</Orig_str>
    <ENG>Subgroup 6</ENG>
  <Orig_str>Sottogruppo 7</Orig_str>
    <ENG>Subgroup 7</ENG>
  <Orig_str>Sottogruppo 8</Orig_str>
    <ENG>Subgroup 8</ENG>
  <Orig_str>Sottogruppo 9</Orig_str>
    <ENG>Subgroup 9</ENG>
  <Orig_str>Sottogruppo Att. Ec.</Orig_str>
    <ENG>Economic Group</ENG>
  <Orig_str>Spedito Agenzia Entrate</Orig_str>
    <ENG>Sended to Tax Agency</ENG>
  <Orig_str>Spedizione Chiusura</Orig_str>
    <ENG>Closed Sending</ENG>
  <Orig_str>Stampa Analitica</Orig_str>
    <ENG>Analytic Report</ENG>
  <Orig_str>Stampa Persone / Società / Fornitori (Report)</Orig_str>
    <ENG>Subjects Report</ENG>
  <Orig_str>Stampa Rapporti + Dettaglio Operazioni</Orig_str>
    <ENG>TRANSACTIONS UNDER 15000</ENG>
  <Orig_str>Stampa Sintetica</Orig_str>
    <ENG>Short Report</ENG>
  <Orig_str>Stampa Storico Variazioni</Orig_str>
    <ENG>Historical Variations Report</ENG>
  <Orig_str>Stampa anche le note</Orig_str>
  <Orig_str>Stampa anche se esito negativo</Orig_str>
  <Orig_str>Stati</Orig_str>
    <ENG>Countries</ENG>
  <Orig_str>Stato</Orig_str>
    <ENG>Country</ENG>
  <Orig_str>Stato Intermediario C/Parte</Orig_str>
    <ENG>Other Fincancial Operator State</ENG>
  <Orig_str>Stato Registrazione</Orig_str>
    <ENG>Registration State</ENG>
  <Orig_str>Stato di Nascita</Orig_str>
    <ENG>Birth Country</ENG>
  <Orig_str>Stato di nascita</Orig_str>
    <ENG>Birth Country</ENG>
  <Orig_str>Stato registrazione</Orig_str>
    <ENG>Registration State</ENG>
  <Orig_str>Storico Operazioni</Orig_str>
    <ENG>Historical Transactions</ENG>
  <Orig_str>Storico Rapporti</Orig_str>
    <ENG>Historical Business Contracts</ENG>
  <Orig_str>Storico Variazioni</Orig_str>
    <ENG>Historical Modifies </ENG>
  <Orig_str>TABELLA</Orig_str>
    <ENG>TABLE</ENG>
  <Orig_str>Tabella</Orig_str>
    <ENG>Table</ENG>
  <Orig_str>Tipi Documento</Orig_str>
    <ENG>Document Types</ENG>
  <Orig_str>Tipi Legame</Orig_str>
    <ENG>Link Types</ENG>
  <Orig_str>Tipo</Orig_str>
    <ENG>Type</ENG>
  <Orig_str>Tipo Ag. Entrate</Orig_str>
    <ENG>Tax Agency Code</ENG>
  <Orig_str>Tipo Divisa</Orig_str>
    <ENG>Lire Euro Currency</ENG>
  <Orig_str>Tipo Documento</Orig_str>
    <ENG>Document Type</ENG>
  <Orig_str>Tipo Informazione</Orig_str>
    <ENG>Information Type</ENG>
  <Orig_str>Tipo Intermediario</Orig_str>
    <ENG>Company Type</ENG>
  <Orig_str>Tipo Intermediario C/Parte</Orig_str>
    <ENG>Oth. Financial Comp. Type</ENG>
  <Orig_str>Tipo Legame</Orig_str>
    <ENG>Link Type</ENG>
  <Orig_str>Tipo Legame Sogg.</Orig_str>
    <ENG>Subject Link Type</ENG>
  <Orig_str>Tipo Legame sogg. Operante</Orig_str>
    <ENG>Subject Link Type</ENG>
  <Orig_str>Tipo Operazione Agenzia Entrate</Orig_str>
    <ENG>Tax Agency Operation Type</ENG>
  <Orig_str>Tipo Operazione Completa</Orig_str>
    <ENG>Transaction Type</ENG>
  <Orig_str>Tipo Operazione</Orig_str>
    <ENG>Transaction Type</ENG>
  <Orig_str>Tipo Persona</Orig_str>
    <ENG>Subject Type</ENG>
  <Orig_str>Tipo Rap. Ag. Entrate</Orig_str>
    <ENG>Financial Ag. Type</ENG>
  <Orig_str>Tipo Rapporto</Orig_str>
    <ENG>Business Contract Type</ENG>
  <Orig_str>Tipo Rapporto Beneficiario</Orig_str>
    <ENG>Recipient Contract Type</ENG>
  <Orig_str>Password</Orig_str>
    <ENG>Password</ENG>
  <Orig_str>Tipo Rapporto UIC</Orig_str>
    <ENG>Business Contract Type</ENG>
  <Orig_str>Tipo Registrazione</Orig_str>
    <ENG>Registration Type</ENG>
  <Orig_str>Tipo Soggetto</Orig_str>
    <ENG>Subject Type</ENG>
  <Orig_str>Tipo Telgame</Orig_str>
    <ENG>Link Type</ENG>
  <Orig_str>Tipo di Ricerca</Orig_str>
    <ENG>Search Type</ENG>
  <Orig_str>Tipo intermediario</Orig_str>
    <ENG>Company Type</ENG>
  <Orig_str>Tipo operazione</Orig_str>
    <ENG>Transaction Type</ENG>
  <Orig_str>Tipologia</Orig_str>
    <ENG>Type</ENG>
  <Orig_str>Tipologia Utenti</Orig_str>
    <ENG>Users Type</ENG>
  <Orig_str>Tipologia intermediari</Orig_str>
    <ENG>Companies Type</ENG>
  <Orig_str>Tipologie  legami</Orig_str>
    <ENG>Links Type</ENG>
  <Orig_str>Tipologie Intermediario</Orig_str>
    <ENG>Companies Type</ENG>
  <Orig_str>Tipologie Rapporto</Orig_str>
    <ENG>Contracts Type</ENG>
  <Orig_str>Tot.Lire/Euro</Orig_str>
    <ENG>Tot. Lire/Euro</ENG>
  <Orig_str>Totale</Orig_str>
    <ENG>Total</ENG>
  <Orig_str>Totale Contanti</Orig_str>
    <ENG>Cash Total</ENG>
  <Orig_str>Totale Operazione</Orig_str>
    <ENG>Transaction Value</ENG>
  <Orig_str><![CDATA[>]]></Orig_str>
  <Orig_str>Totali in Euro</Orig_str>
    <ENG>Total in EURO</ENG>
  <Orig_str>Totali in Lire</Orig_str>
    <ENG>Total Lire</ENG>
  <Orig_str>Trasferimento Archivi periodo 01/01/2005 - 31/12/2006
per comunicazione del 30/04/07 </Orig_str>
    <ENG>Archive Transfer Period 01/01/2005 - 31/12/2006
for comunication of 30/04/07 </ENG>
  <Orig_str>Trasferimento Archivi periodo 01/01/2005 - 31/12/2007
per comunicazione del 30/06/2008 </Orig_str>
    <ENG>Archive Transfer Period 01/01/2005 - 31/12/2007
for comunication of 30/06/2008 </ENG>
  <Orig_str>Trasferimento Archivi periodo 01/01/2007 - 30/04/2007
per comunicazione del 31/05/07 </Orig_str>
    <ENG>Archives Transfer Period 01/01/2007 - 30/04/2007
for comunication of 31/05/07 </ENG>
  <Orig_str>Trasferimento Archivi periodo 01/01/2008 - 30/06/2008
per comunicazione del 31/07/2008 </Orig_str>
    <ENG>Archives Transfer Period 01/01/2008 - 30/06/2008
for comunication of 31/07/2008</ENG>
  <Orig_str>Trasferimento Periodico Mensile</Orig_str>
    <ENG>Periodical Monthly Transfer</ENG>
  <Orig_str>Trasferimento Rapporti a Storico</Orig_str>
    <ENG>Contracts Historical Transfer</ENG>
  <Orig_str>Trasferimento archivio per invio iniziale</Orig_str>
    <ENG>Sending Archive for first communication</ENG>
  <Orig_str>Trasferimento archivio per secondo invio </Orig_str>
    <ENG>Sending Archive for second communication</ENG>
  <Orig_str>Trasferimento operazioni a Storico</Orig_str>
    <ENG>Transactions Historical Transfer</ENG>
  <Orig_str>Trasmessa</Orig_str>
    <ENG>Sended</ENG>
  <Orig_str>Trasmesso</Orig_str>
    <ENG>Sended</ENG>
  <Orig_str>Trasmesso con il file</Orig_str>
    <ENG>Sended with File</ENG>
  <Orig_str>URL Applicazione</Orig_str>
    <ENG>Application URL:</ENG>
  <Orig_str>UTENTE</Orig_str>
    <ENG>USER</ENG>
  <Orig_str>Ultima Data Accesso</Orig_str>
    <ENG>Last Login Date</ENG>
  <Orig_str>Utente Procedura</Orig_str>
    <ENG>Procedure User</ENG>
  <Orig_str>Utente SP</Orig_str>
    <ENG>Internal User</ENG>
  <Orig_str>Utente SitePainter</Orig_str>
    <ENG>User Type</ENG>
  <Orig_str>Valido per tipo intermediario</Orig_str>
    <ENG>Valid for Company Type</ENG>
  <Orig_str>Valore inferiore ai minimi richiesti ( €15.000, € 12.500, € 10.319,14, £ 20.000.000)</Orig_str>
    <ENG>Value under minimum needed ( € 15,000, € 12,500, € 10,319.14, £ 20,000,000)</ENG>
  <Orig_str>Valore superiore ai massimi richiesti ( €15.000, € 12.500, € 10.319,14, £ 20.000.000)</Orig_str>
    <ENG>Value over maximum needed ( € 15,000, € 12,500, € 10,319.14, £ 20,000,000)</ENG>
  <Orig_str>Valuta</Orig_str>
    <ENG>Currency</ENG>
  <Orig_str>Valuta Estera</Orig_str>
    <ENG>Currency</ENG>
  <Orig_str>Valuta Estera Transitoria</Orig_str>
    <ENG>Currency</ENG>
  <Orig_str>Valute</Orig_str>
    <ENG>Currencies</ENG>
  <Orig_str>Valute / Divise</Orig_str>
    <ENG>Currencies</ENG>
  <Orig_str>Vecchia Natura</Orig_str>
    <ENG>Old Type</ENG>
  <Orig_str>Vecchia Password</Orig_str>
    <ENG>Old Password</ENG>
  <Orig_str>Vecchia Tipologia</Orig_str>
    <ENG>Old Type</ENG>
  <Orig_str>Vecchio Intestatario</Orig_str>
    <ENG>Old Owner</ENG>
  <Orig_str>Vecchio Progressivo</Orig_str>
    <ENG>Old ID Number</ENG>
  <Orig_str>Vecchio file spedizione chiusura</Orig_str>
    <ENG>Closing Old File Name</ENG>
  <Orig_str>Via A. Murri,6 - 51016 Montecatini Terme (PT) - Tel. 0572/766141 Fax. 0572/766195. 
 Altre sedi Firenze Forli  Milano.

</Orig_str>
  <Orig_str>Vista Informazioni</Orig_str>
    <ENG>Informations View</ENG>
  <Orig_str>Visualizza Frazionarie A.U.I.</Orig_str>
  <Orig_str>Visualizza Operazioni A.U.I.</Orig_str>
  <Orig_str>Visualizza Operazioni Provvisorie</Orig_str>
  <Orig_str>Visualizza Rapporti A.U.I</Orig_str>
  <Orig_str>Visualizza Rapporti Provvisori</Orig_str>
  <Orig_str>Visualizzazione Dettagli</Orig_str>
    <ENG>Details View</ENG>
  <Orig_str>data Inizio</Orig_str>
    <ENG>Start Date</ENG>
  <Orig_str>di cui Contanti</Orig_str>
    <ENG>Cash Part</ENG>
  <Orig_str>di cui contanti</Orig_str>
    <ENG>Cash Part</ENG>
  <Orig_str>email</Orig_str>
  <Orig_str>idbase</Orig_str>
  <Orig_str>ramgru</Orig_str>
  <Orig_str>ultima data accesso</Orig_str>
    <ENG>Last Login Date</ENG>
  <Orig_str>User</Orig_str>
    <ENG>User</ENG>
  <Orig_str>F11. Beneficiario</Orig_str>
  <Orig_str>F13. Codice Paese Beneficiario</Orig_str>
  <Orig_str>Impossibile modificare operazioni in archivio storico</Orig_str>
    <ENG>Impossible to modify operation in historical archive</ENG>
  <Orig_str>Note</Orig_str>
    <ENG>Notes</ENG>
  <Orig_str><![CDATA[>=]]></Orig_str>
  <Orig_str><![CDATA[<=]]></Orig_str>
  <Orig_str>No</Orig_str>
  <Orig_str>Tipo Rapporto Collegato</Orig_str>
    <ENG>Linked Contract Type</ENG>
  <Orig_str>Totale Operazioni</Orig_str>
    <ENG>Transactions Value</ENG>
  <Orig_str>+</Orig_str>
</TRANSLATED_STRINGS>
