var SPTheme={
  colTabCanCollapse:true,
  colTabUseSeparator:false,
  formGridBorderWidth:1,
  formTabAutoSelect:false,
  formTabCanCollapse:true,
  formTabUseGradient:false,
  formTabUseSeparator:false,
  grid_img_navbar_add_rows:"../portalstudio/images/grid_plus.png",
  grid_img_navbar_first:"../portalstudio/images/grid_first.png",
  grid_img_navbar_first_dis:"../portalstudio/images/grid_first_dis.png",
  grid_img_navbar_last:"../portalstudio/images/grid_last.png",
  grid_img_navbar_last_dis:"../portalstudio/images/grid_last_dis.png",
  grid_img_navbar_next:"../portalstudio/images/grid_next.png",
  grid_img_navbar_next_dis:"../portalstudio/images/grid_next_dis.png",
  grid_img_navbar_prev:"../portalstudio/images/grid_prev.png",
  grid_img_navbar_prev_dis:"../portalstudio/images/grid_prev_dis.png",
  grid_img_navbar_rem_rows:"../portalstudio/images/grid_minus.png",
  grid_img_refresh:"../portalstudio/images/grid_refresh.png",
  grid_img_filter_addnew:"{\"Char\":\"60397\",\"Color\":\"#FFFFFF\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"18\"}",
  grid_img_filter_apply:"{\"Char\":\"61323\",\"Color\":\"#FFFFFF\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"18\"}",
  grid_img_filter_by_example:"{\"FontName\":\"fontawesome-webfont\",\"Char\":\"61761\",\"Size\":\"14\",\"Color\":\"rgba(0,0,0,0.87)\"}",
  grid_img_filter_by_example_delete:"{\"Char\":\"61359\",\"Color\":\"\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"22\"}",
  grid_img_filter_by_example_position:"bottom",
  grid_img_filter_close:"{\"Char\":\"61512\",\"Color\":\"#FFFFFF\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"18\"}",
  grid_img_filter_delete:"{\"Char\":\"61505\",\"Color\":\"rgba(255,255,255,0.87)\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"22\"}",
  grid_img_filter_disable:"{\"Char\":\"62035\",\"Color\":\"rgba(255,255,255,0.87)\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"normal\",\"Size\":\"22\"}",
  grid_img_filter_open:"../Fusion/images/filter.png",
  // modalZoomBorderWidth:1,
  // modalZoomBorderColor:'#CCCCCC',
  activateModalZoom:false,
//entryEffectModalLayer:"none",
  modalMaskBgColor:"#000000",
  modalMaskClickClose:true,
  modalMaskOpacity:70,
  modalMaskScrollbars:true,
  modalZoomBorderColor:"rgba(0,0,0,.5)",
  modalZoomBorderWidth:0,
  modalZoomCloseImage:"{\"Char\":\"61512\",\"Color\":\"#FFFFFF\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"\",\"Size\":\"18\"}",
  modalZoomDrag:true,
  modalZoomHeight:480,
  modalZoomResize:true,
  modalZoomWidth:520,
  //spModalLayerResizeImg:"../portalstudio/images/panel/resize.png",
  // activateModalPopup:true,
  entryEffectModalLayer:"none",
  formTabUseGradient: true,
  formTabUseSeparator: false,
  modalMaskScrollbars:true,
  portalstudioTabstrip:{
    formTabAutoSelect:false,
    formTabCanCollapse:false,
    formTabCollapse:"{\"Char\":\"62149\",\"Color\":\"rgba(0,0,0,.87)\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"600\",\"Size\":\"20\"}",
    formTabExpand:"{\"Char\":\"62148\",\"Color\":\"rgba(0,0,0,.15)\",\"FontName\":\"icons8_win10\",\"FontWeight\":\"600\",\"Size\":\"20\"}",
    formTabH:35,
    formTabUseGradient:true,
    formTabUseSeparator:false
  }
};
if (typeof(ZtVWeb)!='undefined')
  ZtVWeb.theme='portalstudio';


