<?xml version="1.0" encoding="ISO-8859-1"?>
<!-- Example:
  <Orig_str>stringa originale</Orig_str>
    <ITA>Traduzione</ITA>
    .
    .
    <JAP><![CDATA[String with special chars: <>&]]></JAP>
    .
    .
    <ENG>Translation</ENG>
-->
<TRANSLATED_STRINGS>
  <Orig_str>Add new security</Orig_str>
    <SPA>Añadir seguridad</SPA>
    <ITA>Aggiungi sicurezza</ITA>
    <FRA>Ajoutez la sécurité</FRA>
    <DEU>Neue Sicherheiten hinzufügen</DEU>
    <RON>Adaugati securitatea</RON>
    <ENG>Add security</ENG>
  <Orig_str>All</Orig_str>
    <SPA>Todos</SPA>
    <ITA>Tutti</ITA>
    <FRA>Tous</FRA>
    <DEU>Alle</DEU>
    <RON>Toate</RON>
    <ENG>All</ENG>
  <Orig_str>Allow Execute</Orig_str>
    <SPA>Permitir ejecución</SPA>
    <ITA>Permetti esecuzione</ITA>
    <FRA><![CDATA[Permettez l'exécution]]></FRA>
    <DEU>Ausführen zulassen</DEU>
    <RON>Permiteti executarea</RON>
    <ENG>Allow the execution</ENG>
  <Orig_str>Ascending</Orig_str>
    <SPA>Ascendente</SPA>
    <ITA>Ascendente</ITA>
    <FRA>Croissant</FRA>
    <DEU>Aufsteigend</DEU>
    <RON>Ascendent</RON>
    <ENG>Ascending</ENG>
  <Orig_str>Attention: System tables are not administrated.
Please, run the system tables administration before using the current option.</Orig_str>
    <SPA>Atención: no se administran las tablas de sistema.
Hay que llevar a cabo la administración de las tablas de sistema antede usar la gestión seleccionada.</SPA>
    <ITA><![CDATA[Attenzione: le tabelle di sistema non sono amministrate.
Bisogna eseguire l'amministrazione delle tabelle di sistema prima di usare la gestione selezionata.]]></ITA>
<FRA><![CDATA[Attention ! Les tableaux de système ne sont pas administrés.
Il est nécessaire d'exécuter l'administration des tableaux de système avant d'utiliser la gestion sélectionnée.]]></FRA>
    <DEU>Warnung: Systemtabellen sind nicht verwaltet.
Vor der Verwendung der ausgewählten Verwaltung muss die Verwaltung der Systemtabellen ausgeführt werden.</DEU>
<RON>Atentie! Tabelele de sistem nu sunt administrate.
Trebuie efectuata administrarea tabelelor de sistem inainte de a utiliza gestiunea selectata.</RON>
<ENG>Warning! The system tables are not administered. It is necessary to administer the system tables before using the selected management.</ENG>
  <Orig_str>Block Execute</Orig_str>
    <SPA>Bloquear ejecución</SPA>
    <ITA>Blocca esecuzione</ITA>
    <FRA><![CDATA[Bloquez l'exécution]]></FRA>
    <DEU>Ausführung sperren</DEU>
    <RON>Blocati executarea</RON>
    <ENG>Block execute</ENG>
  <Orig_str>Data name</Orig_str>
    <SPA>Nombre datos</SPA>
    <ITA>Nome logico</ITA>
    <FRA>Nom logique</FRA>
    <DEU>Datenname</DEU>
    <RON>Denumire logica</RON>
    <ENG>Logical name</ENG>
  <Orig_str>Database administration script created</Orig_str>
    <SPA>Se creó el script de administración de la base de datos</SPA>
    <ITA>Script di amministrazione database creato</ITA>
    <FRA><![CDATA[Script d'administration de la base de données créée]]></FRA>
    <DEU>Skript der Datenbankverwaltung wurde erstellt</DEU>
    <RON>Script de administrare a bazei de date create</RON>
    <ENG>Created database administration script</ENG>
  <Orig_str>Database server
(empty=Default)</Orig_str>
    <SPA>Servidor de la base de datos
 (vacío=defecto)</SPA>
    <ITA>Server di database
(vuoto=default)</ITA>
  <FRA>Serveur base de données
(vide=défaut)</FRA>
    <DEU>Datenbankserver
(leer=Standard)</DEU>
<RON>Server baza de date
(gol=implicit)</RON>
<ENG>Database server (void = default)</ENG>
  <Orig_str>Descending</Orig_str>
    <SPA>Descendente</SPA>
    <ITA>Discendente</ITA>
    <FRA>Décroissant</FRA>
    <DEU>Absteigend</DEU>
    <RON>Descendent</RON>
    <ENG>Descending</ENG>
  <Orig_str>Entity name</Orig_str>
    <SPA>Nombre entidad</SPA>
    <ITA>Nome entità</ITA>
    <FRA>Nom entité</FRA>
    <DEU>Name der Entität</DEU>
    <RON>Denumire entitate</RON>
    <ENG>Entity name</ENG>
  <Orig_str>Errors while adding language</Orig_str>
    <SPA>Errores al añadir el idioma</SPA>
    <ITA><![CDATA[Errori durante l'aggiunta della lingua]]></ITA>
    <FRA><![CDATA[Erreur lors de l'ajoute de la langue]]></FRA>
    <DEU>Fehler beim Hinzufügen der Sprache</DEU>
    <RON>Erori la adaugarea limbii</RON>
    <ENG>Errors while adding the language</ENG>
  <Orig_str>Errors while deleting company</Orig_str>
    <SPA>Errores al eliminar la empresa</SPA>
    <ITA><![CDATA[Errori durante l'eliminazione dell'azienda]]></ITA>
    <FRA><![CDATA[Erreur lors de l'élimination de l'entreprise]]></FRA>
    <DEU>Fehler beim Löschen der Gesellschaft</DEU>
    <RON>Erori la eliminarea societatii</RON>
    <ENG>Errors while removing the company</ENG>
  <Orig_str>Go back to control panel</Orig_str>
    <SPA>Volver al panel de control</SPA>
    <ITA>Torna al pannello di controllo</ITA>
    <FRA>Retour au panneau de contrôle</FRA>
    <DEU>Zurück zur Systemsteuerung</DEU>
    <RON>Reveniti la panoul de control</RON>
    <ENG>Return to control panel</ENG>
  <Orig_str>If selected, the security record will be applied for all entities</Orig_str>
    <SPA>Si seleccionado, se aplicará la regla de seguridad para todas las entidades</SPA>
    <ITA>Se selezionato, la regola di sicurezza verrà applicata per tutte le entità</ITA>
    <FRA>Si sélectionné, la règle de sécurité sera appliquée pour toutes les entités</FRA>
    <DEU>Wenn ausgewählt, Sicherheitsdatensatz wird auf alle Entitäten angewendet</DEU>
    <RON>Daca este selectata, regula de securitate se va aplica pentru toate entitatile</RON>
    <ENG>If selected, the safety rule will apply for all entities</ENG>
  <Orig_str>Language added successfully</Orig_str>
    <SPA>Idioma añadido correctamente</SPA>
    <ITA>Lingua aggiunta con successo</ITA>
    <FRA>Langue ajoutée avec succès</FRA>
    <DEU>Die Sprache wurde mit Erfolg hinzugefügt</DEU>
    <RON>Limba adaugata cu succes</RON>
    <ENG>Language added successfully</ENG>
  <Orig_str>Last modified</Orig_str>
    <SPA>Última modificación</SPA>
    <ITA>Ultima modifica</ITA>
    <FRA>Dernière modification</FRA>
    <DEU>Zuletzt geändert</DEU>
    <RON>Ultima modificare</RON>
    <ENG>Last modification</ENG>
  <Orig_str>Name of the entity to search</Orig_str>
    <SPA>Nombre de la entidad a buscar</SPA>
    <ITA><![CDATA[Nome dell'entità da cercare]]></ITA>
    <FRA><![CDATA[Nom de l'entité à chercher]]></FRA>
    <DEU>Name der zu suchenden Entität</DEU>
    <RON>Denumirea entitatii de cautat</RON>
    <ENG>Entity name to search</ENG>
 <Orig_str>Physical name</Orig_str>
    <SPA>Nombre físico</SPA>
    <ITA>Nome fisico</ITA>
    <FRA>Nom physique</FRA>
    <DEU>Physikalischer Name</DEU>
    <RON>Denumire fizica</RON>
    <ENG>Physical name</ENG>
  <Orig_str>Run system tables administration now</Orig_str>
    <SPA>Llevar a cabo la administración de las tablas de sistema</SPA>
    <ITA><![CDATA[Esegui l'amministrazione delle tabelle di sistema]]></ITA>
    <FRA><![CDATA[Exécutez l'administration des tableaux de système]]></FRA>
    <DEU>Verwaltung der Systemtabellen jetzt ausführen</DEU>
    <RON>Efectuati administrarea tabelelor de sistem</RON>
    <ENG>Execute the system table administration</ENG>
  <Orig_str>Search for security</Orig_str>
    <SPA>Buscar seguridad</SPA>
    <ITA>Cerca sicurezza</ITA>
    <FRA>Cherchez la sécurité</FRA>
    <DEU>Nach Sicherheit suchen</DEU>
    <RON>Cautati securitate</RON>
    <ENG>Search security</ENG>
  <Orig_str>Server name</Orig_str>
    <SPA>Nombre servidor</SPA>
    <ITA>Nome server</ITA>
    <FRA>Nom du serveur</FRA>
    <DEU>Servername</DEU>
    <RON>Denumire server</RON>
    <ENG>Server name</ENG>
  <Orig_str>System tables already exist</Orig_str>
    <SPA>Tablas de sistema ya creadas</SPA>
    <ITA>Tabelle di sistema già create</ITA>
    <FRA>Tableaux de système déjà créés</FRA>
    <DEU>Die Systemtabellen sind bereits vorhanden</DEU>
    <RON>Tabele de sistem create deja</RON>
    <ENG>System tables already created</ENG>
  <Orig_str>System tables created</Orig_str>
    <SPA>Tablas de sistema creadas</SPA>
    <ITA>Tabelle di sistema create</ITA>
    <FRA>Tableaux de système créés</FRA>
    <DEU>Die Systemtabellen wurden erstellt</DEU>
    <RON>Tabele de sistem create</RON>
    <ENG>Created system tables</ENG>
    <Orig_str>Procedure</Orig_str>
    <SPA>Procedimiento</SPA>
    <ITA>Procedura</ITA>
    <FRA>Procédure</FRA>
    <DEU>Prozedur</DEU>
    <RON>Procedura</RON>
    <ENG>Procedure</ENG>
  <Orig_str>System tables not administrated</Orig_str>
    <SPA>Tablas de sistema no administradas</SPA>
    <ITA>Tabelle di sistema non amministrate</ITA>
    <FRA>Tableaux de système pas administrés</FRA>
    <DEU>Die Systemtabellen sind nicht verwaltet</DEU>
    <RON>Tabele de sistem neadministrate</RON>
    <ENG>System tables not administered</ENG>
  <Orig_str>Table logical name</Orig_str>
    <SPA>Nombre lógico de la tabla</SPA>
    <ITA>Nome logico della tabella</ITA>
    <FRA>Nom logique du tableau</FRA>
    <DEU>Logischer Name der Tabelle</DEU>
    <RON>Denumire logica a tabelului</RON>
    <ENG>Logical table name</ENG>
  <Orig_str>Table physical name</Orig_str>
    <SPA>Nombre físico de la tabla</SPA>
    <ITA>Nome fisico della tabella</ITA>
    <FRA>Nom physique du tableau</FRA>
    <DEU>Physikalischer Tabellename</DEU>
    <RON>Denumire fizica a tabelului</RON>
    <ENG>Physical table name</ENG>
  <Orig_str>Type of the entity to search</Orig_str>
    <SPA>Tipo de entidad a buscar</SPA>
    <ITA>Tipo di entità da cercare</ITA>
    <FRA><![CDATA[Type d'entité à chercher]]></FRA>
    <DEU>Typ der zu suchenden Entität</DEU>
    <RON>Tip de entitate de cautat</RON>
    <ENG>Type of entity to search</ENG>
  <Orig_str>System tables created successfully</Orig_str>
    <SPA>Las tablas de sistema se crearon correctamente</SPA>
    <ITA>Tabelle di sistema create con successo</ITA>
    <FRA>Tableaux de système créés avec succès</FRA>
    <DEU>Die Systemtabellen wurden erfolgreich erstellt</DEU>
    <RON>Tabele de sistem create cu succes</RON>
    <ENG>System tables created successfully</ENG>
<Orig_str>SPAS_APP_USUPPORTED_OS</Orig_str>
    <SPA>La aplicación no está disponible para este sistema</SPA>
    <ITA>Applicazione non disponibile per questo sistema</ITA>
    <FRA>Application indisponible pour ce système</FRA>
    <DEU>Anwendung für dieses System nicht verfügbar</DEU>
    <RON>Aplicatie indisponibila pentru acest sistem</RON>  
    <ENG>Application not suppported for this O.S.</ENG>
 <Orig_str>SPAS_SCAN_QR_INFO</Orig_str>
    <SPA>Escanear la imágen con un dispositivo</SPA>
    <ITA>Scansiona l'immagine con un dispositivo</ITA>
    <FRA><![CDATA[Scannez l'image avec un dispositif]]></FRA>
    <DEU>Bild mit Scanner scannen</DEU>
    <RON>Scanati imaginea cu un dispozitiv</RON>
    <ENG>Scan image with a device</ENG>
  <Orig_str>SPAS_DOWNLOAD_ENTERPRISEAPPSTORE_APP</Orig_str>
    <SPA>Tiempo de espera descarga App Infinity</SPA>
    <ITA>Scarica Infinity App Runtime</ITA>
    <FRA>Téléchargez Infinity App Runtime</FRA>
    <DEU>Infinity App-Runtime herunterladen</DEU>
    <RON>Descarcati Infinity App Runtime</RON>
    <ENG>Download Infinity App Runtime</ENG>
  <Orig_str>MOBAPPSTORE_ACCESS_MODE</Orig_str>
    <SPA>Modo de acceso</SPA>
    <ITA>Modalità di accesso</ITA>
    <FRA><![CDATA[Modalité d'accès]]></FRA>
    <DEU>Zugriffsmodus</DEU>
    <RON>Modalitate de acces</RON>
    <ENG>Access mode</ENG>
  <Orig_str>MSG_MOBAPPSTORE_ACCESS_MODE_BROWSER</Orig_str>
    <SPA>Navegador solo</SPA>
    <ITA>Solo browser</ITA>
    <FRA>Seulement navigateur</FRA>
    <DEU>Nur Browser</DEU>
    <RON>Doar browser</RON>
    <ENG>Browser only</ENG>
  <Orig_str>MSG_MOBAPPSTORE_ACCESS_MODE_HYBRID</Orig_str>
    <SPA>App híbrida</SPA>
    <ITA>App ibrida</ITA>
    <FRA>Application hybride</FRA>
    <DEU>Hybridanwendung</DEU>
    <RON>Aplicatie hibrida</RON>
    <ENG>Hybrid app</ENG>
  <Orig_str>MSG_MOBAPPSTORE_ACCESS_MODE_BROWSER_AND_HYBRID</Orig_str>
    <SPA>Navegador y app híbrida</SPA>
    <ITA>Browser e app ibrida</ITA>
    <FRA>Navigateur et application hybride</FRA>
    <DEU>Browser und Hybridanwendung</DEU>
    <RON>Browser si aplicatie hibrida</RON>
    <ENG>Browser and hybrid app</ENG>
  <Orig_str>MOBAPPSTORE_PUBLISHED</Orig_str>
    <SPA>Publicada</SPA>
    <ITA>Pubblicata</ITA>
    <FRA>Publiée</FRA>
    <DEU>Veröffentlicht</DEU>
    <RON>Publicata</RON>
    <ENG>Published</ENG>
  <Orig_str>MOBAPPSTORE_DESIGNEDFOR</Orig_str>
    <SPA>Diseñada por</SPA>
    <ITA>Disegnata per</ITA>
    <FRA>Désignée pour</FRA>
    <DEU>Entwickelt für</DEU>
    <RON>Desemnata pentru</RON>
    <ENG>Designed for</ENG>
  <Orig_str>MOBAPPSTORE_BOTHDEVICE</Orig_str>
    <SPA>Ambos</SPA>
    <ITA>Entrambi</ITA>
    <FRA>Les deux</FRA>
    <DEU>Beide</DEU>
    <RON>Ambele</RON>
    <ENG>Both</ENG>
  <Orig_str>MOBAPPSTORE_REQUIRE_REGISTRATION</Orig_str>
    <SPA>Requiere el registro</SPA>
    <ITA>Richiede registrazione</ITA>
    <FRA><![CDATA[Demande l'enregistrement]]></FRA>
    <DEU>Registrierung erforderlich</DEU>
    <RON>Solicita inregistrare</RON>
    <ENG>Require registration</ENG>
  <Orig_str>MOBAPPSTORE_URL_REGISTRATION</Orig_str>
    <SPA>Url de registro</SPA>
    <ITA>Url di registrazione</ITA>
    <FRA><![CDATA[Url d'enregistrement]]></FRA>
    <DEU>Registrierungs-URL</DEU>
    <RON>Url de inregistrare</RON>
    <ENG>Url registration</ENG>
  <Orig_str>MSG_WEBMENU_SAFETY</Orig_str>
    <SPA>Configure la seguridad del menú: %1</SPA>
    <ITA>Imposta le sicurezze del menu: %1</ITA>
	<FRA>Configurez les sécurités du menu : %1</FRA>
	<DEU>Menü-Sicherheit einstellen: %1</DEU>
	<RON>Seta&#539;i elementele de securitate ale meniului: %1</RON>
    <ENG>Sets the menu securities: %1</ENG>
  <Orig_str>MSG_RESOURCE_SAFETY</Orig_str>
	<SPA>Seguridad de los elementos de procedimiento: %1</SPA>
    <ITA>Sicurezza degli elementi di procedura: %1</ITA>
    <FRA>Sécurité des éléments de procédure: %1</FRA>
    <DEU>Sicherheit der Verfahrenselemente: %1</DEU>
    <RON>Securitatea elementelor de procedura: %1</RON>
    <ENG>Safety elements of procedure: %1</ENG>
  <Orig_str>MSG_SELECT_RESOURCE_TO_MANAGE</Orig_str>
    <SPA>Seleccione el procedimiento para gestionar</SPA>
    <ITA>Seleziona la procedura da gestire</ITA>
	<FRA>Sélectionnez la procédure à gérer</FRA>
	<DEU>Zu verwaltende Prozedur auswählen</DEU>
	<RON>Selecta&#539;i procedura de gestionat</RON>
    <ENG>Select the procedure to be managed</ENG>
  <Orig_str>MSG_INITIALIZATION_NOT_DID</Orig_str>
    <SPA>Inicialización no realizada correctamente</SPA>
    <ITA>Inizializzazione non avvenuta correttamente</ITA>
	<FRA>Initialisation pas achevée correctement</FRA>
	<DEU>Die Initialisierung konnte nicht erfolgreich durchgeführt werden</DEU>
	<RON>Ini&#539;ializarea nu a avut loc corect</RON>
    <ENG>Not occurred initializing</ENG>
  <Orig_str>MSG_SECURITY_NOT_MODIFIED</Orig_str>
    <SPA>Estado del elemento no modificado.</SPA>
    <ITA><![CDATA[Stato dell'elemento non modificato.]]></ITA>
	<FRA>État de l&apos;élément pas changé.</FRA>
	<DEU>Der Status des Elements wurde nicht verändert.</DEU>
	<RON>Starea elementului nu a fost modificata.</RON>
    <ENG>Unmodified element status.</ENG>
  <Orig_str>MSG_ELEMENT_WITHOUT_SECURITY</Orig_str>
    <SPA>El elemento no se encuentra bajo seguridad, todos los usuarios tienen acceso.</SPA>
    <ITA><![CDATA[L\'elemento non è più sotto sicurezza, tutti gli utenti hanno accesso.]]></ITA>
	<FRA>L&apos;élément n&apos;est plus sûr, tous les utilisateurs ont accès.</FRA>
	<DEU>Das Element unterliegt nicht mehr der Sicherheitsstufe, alle Benutzer haben Zugang.</DEU>
	<RON>Elementul nu mai este în siguran&#539;a, toti utilizatorii au acces.</RON>
    <ENG>The element is no longer under security, all users have access.</ENG>
  <Orig_str>MSG_SELECT_SUBJECT</Orig_str>
    <SPA>Seleccione el sujeto</SPA>
    <ITA>Seleziona il soggetto</ITA>
	<FRA>Sélectionnez le Sujet</FRA>
	<DEU>Person auswählen</DEU>
	<RON>Selecta&#539;i Subiectul</RON>
    <ENG>Select the subject</ENG>
  <Orig_str>MSG_SHOW_HIDDEN_ITEMS_FOR_SUBJECT</Orig_str>
    <SPA>Mostrar los elementos escondidos</SPA>
    <ITA>Visualizza gli elementi nascosti</ITA>
	<FRA>Visualisez les éléments cachés</FRA>
	<DEU>Verborgene Elemente anzeigen</DEU>
	<RON>Vizualiza&#539;i elementele ascunse în func&#539;ie</RON>
    <ENG>Show hidden items for the subject</ENG>
  <Orig_str>MSG_ADD_USER_TO_ROLE</Orig_str>
    <SPA>Añadir rol al sujeto</SPA>
    <ITA>Aggiungi ruolo al soggetto</ITA>
	<FRA>Ajoutez le rôle au Sujet</FRA>
	<DEU>Der Person eine Rolle hinzufügen</DEU>
	<RON>Adauga&#539;i rolul la Subiect</RON>
    <ENG>Add role to the subject</ENG>
  <Orig_str>MSG_PULL_USER_FROM_ROLE</Orig_str>
    <SPA>Eliminar rol del sujeto</SPA>
    <ITA>Rimuovi ruolo al soggetto</ITA>
	<FRA>Éliminez le rôle au Sujet</FRA>
	<DEU>Eine Rolle von der Person entfernen</DEU>
	<RON>Elimina&#539;i rolul de la Subiect</RON>
    <ENG>Remove role from the subject</ENG>
  <Orig_str>MSG_SIMULATE_ADDING_ROLE</Orig_str>
    <SPA>Simular adición del rol</SPA>
    <ITA>Simula aggiunta del ruolo</ITA>
	<FRA>Simulez l&apos;ajoute du rôle</FRA>
	<DEU>Das Hinzufügen der Rolle simulieren</DEU>
	<RON>Simula&#539;i adaugarea rolului</RON>
    <ENG>Simualates adding the role</ENG>
  <Orig_str>MSG_SIMULATE_REMOVING_ROLE</Orig_str>
    <SPA>Simular eliminación del rol</SPA>
    <ITA>Simula rimozione del ruolo</ITA>
	<FRA>Simulez l&apos;élimination du rôle</FRA>
	<DEU>Das Entfernen der Rolle simulieren</DEU>
	<RON>Simula&#539;i eliminarea rolului</RON>
    <ENG>Simualates removal of the role</ENG>
  <Orig_str>MSG_USER_BELONGS_TO_ROLE</Orig_str>
    <SPA>El usuario ya pertenece al rol.</SPA>
    <ITA>L'utente appartiene già al ruolo.</ITA>
	<FRA>L&apos;utilisateur appartient déjà au rôle.</FRA>
	<DEU>Der Benutzer gehört bereits zu dieser Rolle.</DEU>
	<RON>Utilizatorul apar&#539;ine deja rolului.</RON>
	<ENG>The user has already belonged to the role.</ENG>
  <Orig_str>MSG_USER_NOT_BELONGS_TO_ROLE</Orig_str>
    <SPA>El usuario no pertenece al rol.</SPA>
    <ITA>L'utente non appartiene al ruolo.</ITA>
	<FRA>L&apos;utilisateur n&apos;appartient pas au rôle.</FRA>
	<DEU>Der Benutzer gehört noch nicht zu dieser Rolle.</DEU>
	<RON>Utilizatorul nu apar&#539;ine rolului.</RON>
    <ENG>The user does not belong to the role.</ENG>
  <Orig_str>MSG_USER_NOT_FOUND</Orig_str>
    <SPA>Usuario no encontrado.</SPA>
    <ITA>Utente non trovato.</ITA>
	<FRA>Utilisateur pas trouvé.</FRA>
	<DEU>Benutzer nicht gefunden.</DEU>
	<RON>Utilizator negasit.</RON>
    <ENG>User not found.</ENG>
  <Orig_str>MSG_GROUP_ADDED_SUCCESFULLY</Orig_str>
    <SPA>Grupo añadido con éxito</SPA>
    <ITA>Gruppo aggiunto con successo</ITA>
	<FRA>Groupe ajouté avec succès</FRA>
	<DEU>Gruppe erfolgreich hinzugefügt</DEU>
	<RON>Grup adaugat cu succes</RON>
    <ENG>Group added successfully</ENG>
  <Orig_str>MSG_GROUP_REMOVED_SUCCESFULLY</Orig_str>
    <SPA>Grupo quitado con éxito</SPA>
    <ITA>Gruppo rimosso con successo</ITA>
	<FRA>Groupe éliminé avec succès</FRA>
	<DEU>Gruppe erfolgreich entfernt</DEU>
	<RON>Grup eliminat cu succes</RON>
    <ENG>Group removed successfully</ENG>
  <Orig_str>MSG_SET_START_VALIDITY_GROUP_TODAY</Orig_str>
    <SPA>La fecha de inicio validez ha sido modificada con la de hoy</SPA>
    <ITA>Modificata la data di inizio validità ad oggi</ITA>
	<FRA>La date de début validité a été changée à aujourd&apos;hui</FRA>
	<DEU>Anfangsdatum der Gültigkeit auf heute ändern</DEU>
	<RON>S-a modificat data de început a valabilita&#539;ii la azi</RON>
    <ENG>Changed the validity start date to today</ENG>
  <Orig_str>MSG_RESET_END_VALIDITY_GROUP</Orig_str>
    <SPA>Fecha de fin de validez borrada para el grupo</SPA>
    <ITA>Svuotata la data di fine validità per il gruppo</ITA>
	<FRA>La date de fin validité a été supprimée pour le groupe</FRA>
	<DEU>Enddatum der Gültigkeit für die Gruppe geleert</DEU>
	<RON>S-a eliminat data de sfâr&#539;it a valabilita&#539;ii pentru grupul</RON>
    <ENG>Emptied the end date for the group</ENG>
  <Orig_str>MSG_CONFIRM_ROLE_FIRST</Orig_str>
    <SPA>Hace falta confirmar la modificación del rol.</SPA>
    <ITA><![CDATA[È necessario confermare la modifica del ruolo.]]></ITA>
	<FRA>Il est nécessaire de confirmer le changement du rôle.</FRA>
	<DEU>Die Änderung der Rolle muss bestätigt werden.</DEU>
	<RON>Modificarea rolului trebuie confirmata.</RON>
    <ENG>You need to confirm the change of the role.</ENG>
  <Orig_str>ADMIN_USER_FULLNAME</Orig_str>
    <SPA>El nombre completo del usuario</SPA>
    <ITA>Il nome completo dell'utente</ITA>
	<FRA>Le nom complet de l&apos;utilisateur</FRA>
	<DEU>Vollständiger Benutzername</DEU>
	<RON>Numele complet al utilizatorului</RON>
    <ENG>The full name of the user</ENG>
  <Orig_str>MSG_ENABLE_MODIFY_PASSWORD</Orig_str>
    <SPA>Acceder</SPA>
    <ITA>Abilita modifica password</ITA>
    <FRA>Activer le changement de mot de passe</FRA>
    <DEU>Passwortänderung aktivieren</DEU>
    <RON>Activa?i schimbarea parolei</RON>
    <ENG>Enable password change</ENG>
  <Orig_str>ADMIN_PWDCOMPLEXITY_LEVEL</Orig_str>
    <SPA>El nivel de complejidad de la contraseña introducida</SPA>
    <ITA>Il livello di complessità della password inserita</ITA>
	<FRA>Le niveau de complexité du mot de passe saisi</FRA>
	<DEU>Komplexitätsgrad des eingegebenen Passworts</DEU>
	<RON>Nivelul de complexitate al parolei introduse</RON>
    <ENG>Password complexity level</ENG>
  <Orig_str>ADMIN_PWDCOMPLEXITY_REACHED</Orig_str>
    <SPA>Nivel de complejidad alcanzado</SPA>
    <ITA>Livello di complessità raggiunto</ITA>
	<FRA>Niveau de complexité atteint</FRA>
	<DEU>Komplexitätsgrad erreicht</DEU>
	<RON>Nivel de complexitate atins</RON>
    <ENG>Complexity level reached</ENG>
  <Orig_str>ADMIN_PWDCOMPLEXITY_MIN</Orig_str>
    <SPA>Nivel mínimo de complejidad exigido</SPA>
    <ITA>Livello minimo di complessità richiesto</ITA>
	<FRA>Niveau minimal de complexité demandé</FRA>
	<DEU>Mindestkomplexitätsgrad erforderlich</DEU>
	<RON>Nivelul minim de complexitate solicitat</RON>
    <ENG>Minimum complexity level reached</ENG>
  <Orig_str>ADMIN_FORCEPWDCHANGE_TOOLTIP</Orig_str>
    <SPA>Forzar el cambio de la contraseña al próximo acceso del usuario</SPA>
    <ITA>Forza il cambio della password al prossimo accesso dell'utente</ITA>
	<FRA>Forcez le changement du mot de passe au prochain accès de l&apos;utilisateur</FRA>
	<DEU>Änderung des Passworts beim nächsten Benutzerzugang erzwingen</DEU>
	<RON>For&#539;a&#539;i schimbarea parolei la urmatorul acces al utilizatorului</RON>
    <ENG>Force the change password on next user access</ENG>
  <Orig_str>ADMIN_DISABLED_USER</Orig_str>
    <SPA>Deshabilitar el usuario</SPA>
    <ITA>Disabilita l'utente</ITA>
	<FRA>Désactivez l&apos;utilisateur</FRA>
	<DEU>Benutzer deaktivieren</DEU>
	<RON>Dezactiva&#539;i utilizatorul</RON>
    <ENG>Disable the user</ENG>
  <Orig_str>ADMIN_USER_LANGUAGE</Orig_str>
    <SPA>Idioma del usuario</SPA>
    <ITA>Lingua dell'utente</ITA>
	<FRA>Langue de l&apos;utilisateur</FRA>
	<DEU>Benutzersprache</DEU>
	<RON>Limba utilizator</RON>
    <ENG>User language</ENG>
  <Orig_str>ADMIN_USER_VALIDITY_START</Orig_str>
    <SPA>Fecha cuando comienza la validez del usuario</SPA>
    <ITA>Data in cui inizia la validità dell'utente</ITA>
	<FRA>Date à laquelle la validité de l&apos;utilisateur commence</FRA>
	<DEU>Anfangsdatum der Benutzergültigkeit</DEU>
	<RON>Data la care începe valabilitatea numelui de utilizator</RON>
    <ENG>User validity start date</ENG>
  <Orig_str>ADMIN_USER_VALIDITY_END</Orig_str>
    <SPA>Fecha cuando vence la validez del usuario</SPA>
    <ITA>Data in cui scade la validità dell'utente</ITA>
	<FRA>Date à laquelle la validité de l&apos;utilisateur expire</FRA>
	<DEU>Enddatum der Benutzergültigkeit</DEU>
	<RON>Data la care expira valabilitatea numelui de utilizator</RON>
    <ENG>User validity end date</ENG>
  <Orig_str>ADMIN_LAST_FAILED_LOGIN_DATETIME</Orig_str>
    <SPA>Fecha y hora del último acceso fallido</SPA>
    <ITA>Data e ora dell'ultimo accesso fallito</ITA>
	<FRA>Date et heure du dernier accès échoué</FRA>
	<DEU>Datum und Uhrzeit des letzten fehlgeschlagenen Zugriffs</DEU>
	<RON>Data &#537;i ora ultimului acces nereu&#537;it</RON>
    <ENG>Date and time of the last failed login</ENG>
  <Orig_str>ADMIN_LAST_SUCCESS_LOGIN_DATETIME</Orig_str>
    <SPA>Fecha y hora del último acceso a la aplicación</SPA>
    <ITA>Data e ora dell'ultimo accesso all'applicazione</ITA>
	<FRA>Date et heure du dernier accès à l&apos;application</FRA>
	<DEU>Datum und Uhrzeit des letzten Zugriffs auf die Anwendung</DEU>
	<RON>Data &#537;i ora ultimului acces la aplica&#539;ie</RON>
    <ENG>Date and time of the last successful login</ENG>
  <Orig_str>ADMIN_PWDCREATE_DATE</Orig_str>
    <SPA>Fecha de creación/modificación de la contraseña actualmente en uso </SPA>
    <ITA>Data di creazione/modifica della password attualmente in uso</ITA>
	<FRA>Date de création / changement du mot de passe utilisé à ce moment</FRA>
	<DEU>Erstellungs-/Änderungsdatum des aktuell verwendeten Passworts</DEU>
	<RON>Data crearii/schimbarii parolei curente</RON>
    <ENG>Date of creation / modification of the password currently in use</ENG>
  <Orig_str>ADMIN_PWDDAYSDURATION_TOOLTIP</Orig_str>
    <SPA>Duración de la contraseña expresada en días</SPA>
    <ITA>Durata della password espressa in giorni</ITA>
	<FRA>Durée du mot de passe exprimée en jours</FRA>
	<DEU>Gültigkeitsdauer des Passworts in Tagen</DEU>
	<RON>Durata parolei exprimata în zile</RON>
    <ENG>Password validity in days</ENG>
  <Orig_str>ADMIN_PWDCICLICITY_TOOLTIP</Orig_str>
    <SPA>Número de contraseñas para cambiar antes de volver a utilizar una antigua</SPA>
    <ITA>Numero di password da cambiare prima di riutilizzarne una vecchia</ITA>
	<FRA>Nombre des mots de passe à changer avant de utiliser de nouveau l&apos;ancien mot de passe</FRA>
	<DEU>Anzahl der Passwörter, die geändert werden müssen, bevor ein altes Passwort wiederverwendet werden kann</DEU>
	<RON>Numarul de parole schimbate înainte de a reutiliza o parola veche</RON>
    <ENG>Number of passwords to be changed before to reuse an old password</ENG>
  <Orig_str>ADMIN_CAPTCHA_LEVEL_TOOLTIP</Orig_str>
    <SPA>Número de accesos fallidos antes de presentar el CAPTCHA</SPA>
    <ITA>Numero di accessi falliti prima di presentare il CAPTCHA</ITA>
	<FRA>Nombre des accès échoués avant d&apos;afficher le code CAPTCHA</FRA>
	<DEU>Anzahl der fehlgeschlagenen Zugriffe, bevor das CAPTCHA angezeigt wird</DEU>
	<RON>Numarul de conectari nereu&#537;ite înainte de a aparea codul CAPTCHA</RON>
    <ENG>Number of failed access before asking the CAPTCHA</ENG>
   <Orig_str>ADMIN_LANG_CODE</Orig_str>
    <SPA>Código ISO del idioma deseado (ej. ENG Inglés, ITA Italiano, DEU Alemán, SPA Español)</SPA>
    <ITA>Codice ISO della lingua desiderata (es. ENG Inglese, ITA Italiano, DEU Tedesco, SPA Spagnolo)</ITA>
	<FRA>Code ISO de la langue souhaitée (par exemple, ENG anglais, ITA italien, DEU allemand, SPA espagnol)</FRA>
	<DEU>ISO-Code der gewünschten Sprache (z.B. ENG Englisch, ITA Italienisch, DEU Deutsch, SPA Spanisch)</DEU>
	<RON>Codul ISO al limbii dorite (de ex., ENG engleza, ITA italiana, DEU germana, SPA spaniola)</RON>
    <ENG>ISO code of the language (es. ENG English, ITA ITalian, DEU Deutsch, SPA Spanish)</ENG>
   <Orig_str>ADMIN_PRINT_CODE</Orig_str>
    <SPA>Código de identificación de la impresora</SPA>
    <ITA>Codice identificativo della stampante</ITA>
    <FRA>Code enregistrement imprimante</FRA>
    <DEU>Identificationscode des Druckers</DEU>
    <RON>Codul imprimantei</RON>
    <ENG>Printer code</ENG>
  <Orig_str>ADMIN_ALL_COMPANIES</Orig_str>
    <SPA>Todas las empresas</SPA>
    <ITA>Tutte le aziende</ITA>
    <FRA>Toutes les entreprises</FRA>
    <DEU>alle Firmen</DEU>
    <RON>Toate societatilor</RON>
    <ENG>All companies</ENG>
  <Orig_str>ADMIN_LIST_OF_COMPANIES</Orig_str>
    <SPA>Lista de empresas</SPA>
    <ITA>Elenco di aziende</ITA>
    <FRA>Liste des entreprises</FRA>
    <DEU>Liste der Firmen</DEU>
    <RON>Lista societatilor</RON>
    <ENG>List of companies</ENG>
<!-- OTP MANAGEMENT-->   
  <Orig_str>OTP_USERS_LIST</Orig_str>
    <ITA>Utenti</ITA>
    <ENG>Users</ENG>  
    <SPA>Usuarios</SPA>
    <FRA>Les utilisateurs</FRA>
    <DEU>Benutzer</DEU>
    <RON>Utilizatori</RON>
  <Orig_str>OTP_DISABLED_SELECT_USER</Orig_str>
    <ITA>Seleziona l'utente a cui disabilitare OTP.</ITA>
    <ENG>Select the user to disable OTP.</ENG>
    <DEU>Wählen Sie den Benutzer aus, um OTP zu deaktivieren</DEU>
    <SPA>Seleccione el usuario para desactivar OTP</SPA>
    <FRA>Sélectionnez l'utilisateur pour désactiver OTP</FRA>
    <RON>Selecta?i utilizatorul pentru a dezactiva OTP</RON>
  <Orig_str>OTP_DISABLED_CONFIRM</Orig_str>
    <ITA>Premi "disattiva" per rimuovere la validazione del OTP alla login.</ITA>
    <ENG>Press 'disable' to remove the validation of the OTP at login.</ENG>
    <DEU>Klicken Sie auf 'deaktivieren', um die OTP-Validierung bei der Anmeldung zu entfernen.</DEU>
    <SPA>Haga clic en 'desactivar' para eliminar la validación de OTP al iniciar sesión.</SPA>
    <FRA>Cliquez sur 'désactiver' pour supprimer la validation OTP lors de la connexion.</FRA>
    <RON>Face?i clic pe 'dezactivare' pentru a elimina validarea OTP la conectare.</RON>
  <Orig_str>OTP_ACTIVATION</Orig_str>
    <ITA>Attivazione effettuata</ITA>
    <ENG>Activation completed</ENG>  
    <DEU>Aktivierung abgeschlossen</DEU>
    <SPA>Activación completada</SPA>
    <FRA>Activation terminée</FRA>
    <RON>Activare finalizata</RON>
  <Orig_str>OTP_DEACTIVATION</Orig_str>
    <ITA>Disattivazione effettuata</ITA>
    <ENG>Deactivation completed</ENG>  
    <DEU>Deaktivierung abgeschlossen</DEU>
    <SPA>Desactivación completada</SPA>
    <FRA>Désactivation terminée</FRA>
    <RON>Dezactivare finalizata</RON>
  <Orig_str>OTP_ENABLED_SELECT_USER</Orig_str>
    <ITA>Seleziona l'utente a cui associare l'attivazione della OTP.</ITA>
    <ENG>Select the user to associate the OTP activation with.</ENG> 
    <DEU>Wählen Sie den Benutzer, mit dem die OTP-Aktivierung verbunden werden soll, aus.</DEU>
    <SPA>Seleccione el usuario al que conectar la activación OTP.</SPA>
    <FRA>Sélectionnez l’utilisateur auquel connecter l’activation OTP.</FRA>
    <RON>Selecta?i utilizatorul la care sa va conecta?i activarea OTP.</RON>
  <Orig_str>OTP_ENABLED_QRCODE</Orig_str>
    <ITA>Inquadra il QRCode con l'applicazione del tuo device per le password one time secondo lo standard TOTP.</ITA>
    <ENG>Frame the QR Code with the application of your device for one-time passwords according to the TOTP standard.</ENG> 
    <DEU>Scannen Sie den QR-Code mit der Anwendung Ihres Geräts, um Einmalkennwörter gemäß dem TOTP-Standard zu erhalten.</DEU>
    <SPA>Escanea el código QR usando la aplicación de tu dispositivo para obtener contraseñas de un solo uso según el estándar TOTP.</SPA>
    <FRA>Scannez le code QR à l'aide de l'application de votre appareil pour obtenir des mots de passe à usage unique selon la norme TOTP.</FRA>
    <RON>Scana?i codul QR folosind aplica?ia dispozitivului dvs. pentru a ob?ine parole unice conform standardului TOTP.</RON>
  <Orig_str>OTP_ENABLED_CODE</Orig_str>
    <ITA>Digita la password proposta dall'applicazione e premi "Verifica" per controllare l'inizializzazione del sistema.</ITA>
    <ENG>Type the password proposed by the application and press "Check" to check the initialization of the system.</ENG> 
    <DEU>Geben Sie das von der Anwendung vorgeschlagene Kennwort ein und drücken Sie 'Prüfen', um die Initialisierung des Systems zu überprüfen.</DEU>
    <SPA>Ingrese la contraseña sugerida por la aplicación y presione 'Verificar' para verificar la inicialización del sistema.</SPA>
    <FRA>Entrez le mot de passe proposé par l'application et appuyez sur 'Vérifier' pour vérifier l'initialisation du système.</FRA>
    <RON>Introduce?i parola sugerata de aplica?ie ?i apasa?i 'Verifica' pentru a verifica ini?ializarea sistemului.</RON>
  <Orig_str>OTP_ENABLED_STEPS</Orig_str>
    <ITA>Segui i passi per attivare OTP</ITA>
    <ENG>Follow the steps to activate OTP</ENG>  
    <DEU>Befolgen Sie die Schritte, um OTP zu aktivieren</DEU>
    <SPA>Siga los pasos para habilitar OTP</SPA>
    <FRA>Suivez les étapes pour activer OTP</FRA>
    <RON>Urma?i pa?ii pentru a activa OTP</RON>  
  <Orig_str>OTP_ENABLED_RESULT_OK</Orig_str>
    <ITA>OTP valida</ITA>
    <ENG>Valid OTP</ENG> 
    <DEU>Gültiges OTP</DEU>
    <SPA>OTP válida</SPA>
    <FRA>OTP valide</FRA>
    <RON>OTP valid</RON> 
  <Orig_str>OTP_ENABLED_RESULT_KO</Orig_str>
    <ITA>OTP errata</ITA>
    <ENG>Wrong OTP</ENG>  
    <DEU>Falsches OTP</DEU>
    <SPA>OTP incorecta</SPA>
    <FRA>OTP incorrect</FRA>
    <RON>OTP incorect</RON>
  <Orig_str>OTP_ENABLED_CONFIRM</Orig_str>
    <ITA>Premi "attiva" per completare la registrazione del OTP.</ITA>
    <ENG>Press "activate" to complete the registration of the OTP.</ENG>  
    <DEU>Drücken Sie 'aktivieren', um die OTP-Aufzeichnung abzuschließen.</DEU>
    <SPA>Presione 'activar' para completar la grabación OTP.</SPA>
    <FRA>Presse à 'activer' pour terminer l'enregistrement OTP.</FRA>
    <RON>Apasa?i 'activare' pentru a finaliza înregistrarea OTP.</RON>
  <Orig_str>OTP_DEACTIVATE</Orig_str>
    <ITA>Disattiva</ITA>
    <ENG>Deactivate</ENG>  
    <DEU>Deaktivieren</DEU>
    <SPA>Desactivar</SPA>
    <FRA>Désactiver</FRA>
    <RON>Dezactivare</RON>
  <Orig_str>OTP_ACTIVATE</Orig_str>
    <ITA>Attiva</ITA>
    <ENG>Activate</ENG>  
    <DEU>Aktivieren</DEU>
    <SPA>Activar</SPA>
    <FRA>Activer</FRA>
    <RON>Activare</RON>
  <Orig_str>OTP_CHECK</Orig_str>
    <ITA>Verifica</ITA>
    <ENG>Check</ENG>  
    <DEU>Überprüfen</DEU>
    <SPA>Controlar</SPA>
    <FRA>Vérifier</FRA>
    <RON>Verifica</RON>

<!-- END OTP MANAGEMENT-->  
<!-- APPSTORE MASTER REGISTRATION-->   
  <Orig_str>MOBAPPSTORE_TYPE_SYSTEM</Orig_str>
    <SPA>Aplicación del sistema</SPA>
    <ITA>Applicazione di sistema</ITA>
    <FRA>Application du système</FRA>
    <DEU>Systemanwendung</DEU>
    <RON>Aplicarea sistemului</RON>
    <ENG>System application</ENG>
  <Orig_str>MOBAPPSTORE_TYPE_USER</Orig_str>
    <SPA>Aplicación creada por el usuario</SPA>
    <ITA>Applicazione creata da utente</ITA>
    <FRA>Application créée par l'utilisateur</FRA>
    <DEU>Anwendung erstellt von Benutzer</DEU>
    <RON>Aplica&#539;ie creata de utilizator</RON>
    <ENG>Application created by user</ENG>     
  <Orig_str>MOBAPPREG_REGISTRATION</Orig_str>
    <SPA>Registros</SPA>
    <ITA>Registrazioni</ITA>
    <FRA>Enregistrements</FRA>
    <DEU>Registrierungen</DEU>
    <RON>inregistrari</RON>
    <ENG>Registrations</ENG>  
  <Orig_str>MOBAPPREG_CODE</Orig_str>
    <SPA>Código</SPA>
    <ITA>Codice</ITA>
    <FRA>Code</FRA>
    <DEU>Code</DEU>
    <RON>Cod</RON>
    <ENG>Code</ENG>  
  <Orig_str>MOBAPPREG_DT_HR</Orig_str>
    <SPA>Decha y hora</SPA>
    <ITA>Data e ora</ITA>
    <FRA>Date et heure</FRA>
    <DEU>Datum und Uhrzeit</DEU>
    <RON>Data si ora</RON>
    <ENG>Date and time</ENG>    
  <Orig_str>MOBAPPREG_MAIL</Orig_str>
    <SPA>Correo electrónico</SPA>
    <ITA>Mail</ITA>
    <FRA>E-mail</FRA>
    <DEU>E-Mail</DEU>
    <RON>E-mail</RON>
    <ENG>Mail</ENG>  
  <Orig_str>MOBAPPREG_SURNAME_NAME</Orig_str>
    <SPA>Apellido, Nombre</SPA>
    <ITA>Cognome,Nome</ITA>
    <FRA>Nom, Prénom</FRA>
    <DEU>Name, Vorname</DEU>
    <RON>Nume, Prenume</RON>
    <ENG>Surname,Name</ENG>  
  <Orig_str>MOBAPPREG_COMPANY</Orig_str>
    <SPA>Empresa</SPA>
    <ITA>Azienda</ITA>
    <FRA>Entreprise</FRA>
    <DEU>Firma</DEU>
    <RON>Societate</RON>
    <ENG>Company</ENG>  
  <Orig_str>MOBAPPREG_NOTE</Orig_str>
    <SPA>Notas</SPA>
    <ITA>Note</ITA>
    <FRA>Notes</FRA>
    <DEU>Anmerkungen</DEU>
    <RON>Note</RON>
    <ENG>Notes</ENG>  
  <Orig_str>MOBAPPREG_APPURL</Orig_str>
    <SPA>App Url</SPA>
    <ITA>App Url</ITA>
    <FRA>Url application</FRA>
    <DEU>Anwendungs-URL</DEU>
    <RON>Aplicatie Url</RON>
    <ENG>App Url</ENG>  
<!-- END APPSTORE MASTER REGISTRATION-->        
<!-- APPSTORE REGISTRATION-->    
  <Orig_str>MSG_APPREG_WELCOME</Orig_str>
    <SPA>Bienvenido a la demo de %1</SPA>
    <ITA>Benvenuto nella demo di %1</ITA>
    <FRA>Bienvenu au démo de %1</FRA>
    <DEU>Herzlich willkommen bei der Demo von %1</DEU>
    <RON>Bine ati venit in demo-ul %1</RON>
    <ENG>Welcome to application demo %1</ENG>  
  <Orig_str>MSG_APPREG_ACCOUNT</Orig_str>
    <SPA>¿Ya tiene una cuenta?</SPA>
	<ITA>Hai già un account?</ITA>
	<FRA>Avez-vous déjà un compte ?</FRA>
	<DEU>Haben Sie bereits ein Konto?</DEU>
	<RON>Ave&#539;i deja un cont?</RON>
    <ENG>Do you have an account for this app?</ENG>    
  <Orig_str>MSG_APPREG_NOACCOUNT</Orig_str>
    <SPA>¿No tienes una cuenta?</SPA>
    <ITA>Non hai un account?</ITA>
    <FRA><![CDATA[N'avez-vous pas un compte ?]]></FRA>
    <DEU>Noch kein Konto?</DEU>
    <RON>Nu aveti un cont?</RON>
    <ENG>Doesn't you?</ENG>          
  <Orig_str>MSG_APPREG_BTNACCOUNT</Orig_str>
    <SPA>Ir a la aplicación</SPA>
    <ITA>Prosegui</ITA>
    <FRA>Continuez</FRA>
    <DEU>Weiter</DEU>
    <RON>Continuati</RON>
    <ENG>Go to app</ENG>              
  <Orig_str>MSG_APPREG_BTNNOACCOUNT</Orig_str>
    <SPA>Registrarse</SPA>
    <ITA>Registrati</ITA>
    <FRA>Enregistrés</FRA>
    <DEU>Anmelden</DEU>
    <RON>Inregistrare</RON>
    <ENG>Register</ENG>                
  <Orig_str>MSG_APPREG_NAMESURNAME</Orig_str>
    <SPA>Nombre, Apellido</SPA>
    <ITA>Nome,Cognome</ITA>
    <FRA>Prénom, Nom</FRA>
    <DEU>Vorname,Name</DEU>
    <RON>Prenume, Nume</RON>
    <ENG>Name,Surname</ENG>                
  <Orig_str>MSG_APPREG_COMPANY</Orig_str>
    <SPA>Empresa</SPA>
    <ITA>Azienda</ITA>
    <FRA>Entreprise</FRA>
    <DEU>Firma</DEU>
    <RON>Societate</RON>
    <ENG>Company</ENG>                
  <Orig_str>MSG_APPREG_MAIL</Orig_str>
    <SPA>Correo electrónico</SPA>
    <ITA>Indirizzo mail</ITA>
    <FRA>Adresse e-mail</FRA>
    <RON>Adresa e-mail</RON>
    <ENG>Mail</ENG>
    <DEU>E-Mail-Adresse</DEU>               
 <Orig_str>MSG_APPREG_NOTE</Orig_str>
    <SPA>Notas</SPA>
    <ITA>Note</ITA>
    <FRA>Notes</FRA>
    <DEU>Anmerkungen</DEU>
    <RON>Note</RON>
    <ENG>Notes</ENG>                
  <Orig_str>MSG_APPREG_REG_COMPLETE</Orig_str>
    <ENG>A mail with app credtentials was sent to the specified address</ENG>                
    <ITA>La mail con le credenziali per l'accesso all'app è stata spedita all'indirizzo specificato</ITA>
    <DEU>Die E-Mail mit App-Anmeldeinformationen wurde an die angegebene Adresse gesendet</DEU>
    <SPA>El correo electrónico con las credenciales para acceder a la aplicación ha sido enviado a la dirección especificada</SPA>
    <FRA>L'e-mail contenant les informations d'identification pour accéder à l'application a été envoyé à l'adresse indiquée</FRA>
    <RON>E-mailul cu acreditarile pentru accesarea aplica?iei a fost trimis la adresa specificata</RON>          
<!-- END APPSTORE REGISTRATION-->
<!-- IAR LICENSE-->
  <Orig_str>SPAS_IAR_LICENSE</Orig_str>
    <SPA>Licencia IAR</SPA>
	<ITA>Licenza IAR</ITA>
	<FRA>Licence IAR</FRA>
	<DEU>IAR-Lizenz</DEU>
	<RON>Licen&#539;a IAR</RON>
    <ENG>IAR license</ENG>
  <Orig_str>SPAS_USES_IAR_LICENSE</Orig_str>
    <SPA>Utilizar licencia</SPA>
	<ITA>Utilizza licenza</ITA>
	<FRA>Licence IAR</FRA>
	<DEU>Lizenz anwenden</DEU>
	<RON>Licen&#539;a IAR</RON>
    <ENG>Uses license</ENG>
 <Orig_str>SPAS_LICENSE_PURCHASED</Orig_str>
    <SPA>Adquiridas</SPA>
	<ITA>Acquistate</ITA>
	<FRA>Achetées</FRA>
	<DEU>Gekauft</DEU>
	<RON>Achizi&#539;ionate</RON>
    <ENG>Purchased</ENG>
 <Orig_str>SPAS_LICENSE_USED</Orig_str>
    <SPA>Utilizadas</SPA>
	<ITA>Utilizzate</ITA>
	<FRA>Utilisées</FRA>
	<DEU>Verwendet</DEU>
	<RON>Utilizate</RON>
    <ENG>Used</ENG>
 <Orig_str>SPAS_LICENSE_AVAILABLE</Orig_str>
    <SPA>Disponibles</SPA>
	<ITA>Disponibili</ITA>
	<FRA>Disponibles</FRA>
	<DEU>Verfügbar</DEU>
	<RON>Disponibili</RON>
    <ENG>Available</ENG>
 <Orig_str>SPAS_LICENSE_TAMPERED_MSG</Orig_str>
    <SPA>Licencia no válida</SPA>
	<ITA>Licenza non valida</ITA>
	<FRA>Licence pas valide</FRA>
	<DEU>Die Lizenz ist nicht gültig</DEU>
	<RON>Licen&#539;a nevalabila</RON>
    <ENG>License not valid</ENG>
    <ITA>Licenza non valida</ITA>
<!-- END IAR LICENSE-->
</TRANSLATED_STRINGS>
