public class armt_kperazboWV extends CallerBRImpl {
  /*  Dichiarazione delle variabili di lavoro: riflettono gli interventi dell'utente
                              o di una procedura nell'applicazione. Vengono utilizzate per aggiornare e
                              interrogare il database collegato.
                            */
  public java.sql.Date w_DATAOPE;
  public String w_CDATOPE;
  public java.sql.Date w_DATAREG;
  public String w_FLAGCONT;
  public String w_TIPOOPRAP;
  public String w_CODANA;
  public String w_CODVOC;
  public String w_FLAGFRAZ;
  public String w_FLAGLIRE;
  public String w_VALUTA;
  public double w_CAMBIO;
  public double w_TOTLIRE;
  public double w_TOTCONT;
  public String w_RAPPORTO;
  public String w_CONNESCLI;
  public String w_CONNESOPER;
  public String w_TIPOLEG;
  public String w_PAGASOGOP;
  public String w_CONNESBEN;
  public String w_CONNALTRO;
  public String w_C_RAG;
  public String w_C_CTA;
  public String w_C_PRV;
  public String w_C_CAP;
  public String w_C_CAB;
  public String w_C_IND;
  public String w_C_STA;
  public String w_TIPOINT2;
  public String w_CODINT2;
  public String w_DESCINTER;
  public String w_PAESE;
  public String w_C_RAPPORTO;
  public String w_CODCAB2;
  public String w_PROV2;
  public String w_DESC2;
  public String w_ZCPARTE;
  public String w_IDBASE;
  //   variabile per il progressivo
  public String op_IDBASE;
  public String w_NUMPROG;
  //   variabile per il progressivo
  public String op_NUMPROG;
  public String w_CODINTER;
  public String w_TIPOINF;
  public String w_IDEREG;
  public String w_CODDIPE;
  public String w_DESCCIT;
  public String w_FLAGRAP;
  public String w_OPRAP;
  public String w_SEGNO;
  public String w_OPERAZMOD;
  public String w_RAPPORTBEN;
  public String w_OPERATORE;
  public String w_AUTOM;
  public java.sql.Date w_DATARETT;
  public String w_COLLEG;
  public String w_FLAGRAP2;
  public String w_STATOREG;
  public String w_PROVINCIA;
  public String w_CODCAB;
  public double w_PRGIMPOPE;
  //   variabile per il progressivo
  public double op_PRGIMPOPE;
  public String w_CDATAOPE;
  public String w_CONNESDOC;
  public String w_MTCN;
  public String w_CDATREG;
  public String w_filtro;
  public String w_tipope;
  public String w_appolire;
  public double w_xTOTLIRE;
  public double w_xTOTCONT;
  public String w_gIntemediario;
  public String w_xdes1;
  public String w_desccauana;
  public String w_xdesccausin;
  public String w_descdiv;
  public String w_xragsocper;
  public String w_xdescrap;
  public String w_xragsocct;
  public String w_xragsocben;
  public String w_xdestipleg;
  public String w_xragint2;
  public String w_xdescpaese2;
  public java.sql.Date w_datpaseuro;
  public String w_xDescDipe;
  public double w_sEdit;
  public String w_gChkDate;
  public String w_errmsg;
  public String w_test;
  public String w_valflg2;
  public String w_gTipInter;
  public String w_gSblocco;
  public String w_xdescmodsvo;
  public String w_xdescareag;
  public String w_xdescplauso;
  public String w_xdesctipor;
  public String w_xdescopeage;
  public String w_xcodfisc;
  public java.sql.Date w_dataoggi;
  public String w_stringaflagrap2;
  public String w_xdescfreq;
  public String w_xdescammo;
  public java.sql.Date w_gDataVaria;
  public String w_gStatus;
  public String w_CITINT;
  public String w_CITDIP;
  public String w_PROVDIP;
  public String w_CABDIP;
  public String w_PROVINT;
  public String w_CABINT;
  public String w_gFlgDoc;
  public String w_xtiporap;
  public String w_dessta;
  public String w_xragsocalt;
  public String w_xdciticon;
  public String w_gFlgWU;
  public double w_prova;
  // variabili che puntano ai figli
  public ardt_clientisaraBO ardt_clientisara;
  public String m_cWv_ardt_clientisara;
  public CPMNTChild[] m_MNTs = new CPMNTChild[]{};
  // variabili per DependsOn
  public String o_filtro;
  public java.sql.Date o_DATAOPE;
  public String o_CDATOPE;
  public String o_FLAGCONT;
  public String o_CODVOC;
  public String o_FLAGLIRE;
  public String o_appolire;
  public String o_RAPPORTO;
  public String o_CONNESCLI;
  public String o_C_CTA;
  public String o_CODINT2;
  public String o_CODINTER;
  public String o_CODDIPE;
  public String op_codazi;
  // variabile contenente i valori per i campi aggiunti e le proprietà dei rispettivi campi
  public XDCFieldValue[] extendedFields = new XDCFieldValue[]{};
}
