public class armt_wutrxchk_auiWV extends CallerBRImpl {
  /*  Dichiarazione delle variabili di lavoro: riflettono gli interventi dell'utente
                              o di una procedura nell'applicazione. Vengono utilizzate per aggiornare e
                              interrogare il database collegato.
                            */
  public double w_TRXCODPRG;
  //   variabile per il progressivo
  public double op_TRXCODPRG;
  public String w_TRSSEGNO;
  public double w_TRXIMPORTO;
  public double w_TRXCONTAN;
  public String w_TRXUNIQUE;
  public String w_TRXCODDIP;
  public String w_TRXCOGCON;
  public String w_TRXNOMCON;
  public String w_TRXDESTIN;
  public String w_TRXMTCN;
  public String w_TRXCODCAS;
  public String w_TRXRECTYPE;
  public String w_TRXCODMAG;
  public String w_TRXCODUNI;
  public String w_TRXFLGAUI;
  public String w_TRXFLGFOR;
  public String w_TRXERROR01;
  public String w_TRXERROR02;
  public String w_TRXERROR03;
  public String w_TRXERROR04;
  public String w_TRXERROR05;
  public String w_TRXERROR06;
  public String w_TRXERROR07;
  public String w_TRXERROR08;
  public String w_TRXERROR09;
  public String w_TRXERROR10;
  public String w_TRXERROR11;
  public String w_TRXERROR12;
  public String w_TRXERROR13;
  public String w_TRXERROR14;
  public String w_TRXERROR15;
  public String w_TRXERROR16;
  public String w_TRXERROR17;
  public String w_TRXERROR18;
  public String w_TRXERROR19;
  public String w_TRXERROR20;
  public String w_TRXERROR21;
  public String w_TRXERROR22;
  public String w_TRXERROR23;
  public String w_TRXERROR24;
  public String w_TRXERROR25;
  public String w_TRXERROR26;
  public String w_TRXERROR27;
  public String w_TRXERROR28;
  public String w_TRXERROR29;
  public String w_TRXERROR30;
  public String w_TRXERROR31;
  public String w_TRXERROR32;
  public String w_TRXERROR33;
  public String w_TRXERROR34;
  public String w_TRXERROR35;
  public String w_TRXERROR36;
  public String w_TRXERROR37;
  public String w_TRXERROR38;
  public String w_TRXERROR39;
  public String w_TRXERROR40;
  public String w_TRXERROR41;
  public String w_TRXERROR42;
  public String w_TRXERROR43;
  public String w_TRXERROR44;
  public String w_TRXERROR45;
  public String w_TRXERROR46;
  public String w_TRXERROR47;
  public String w_TRXERROR48;
  public String w_TRXERROR49;
  public String w_TRXERROR50;
  public String w_TRXCOGNOM;
  public String w_TRXNOME;
  public String w_TRXDOMICI;
  public String w_TRXFLGCF;
  public String w_TRXCODFIS;
  public String w_TRXLUONAS;
  public String w_TRXNUMDOC;
  public java.sql.Date w_TRXDATSCA;
  public java.sql.Date w_TRXDATRIL;
  public String w_TRXAUTRIL;
  public String w_TRXNAZRES;
  public String w_TRXCITRES;
  public String w_TRXTIPDOC;
  public java.sql.Date w_TRXDATNAS;
  public java.sql.Date w_TRXDATOPE;
  public String w_TRXSESSO;
  public String w_TRXNASSTATO;
  public String w_TRXNASCOMUN;
  public String w_TRXFLGCON;
  public String w_xMADESCRI;
  public String w_xDESCRIZ;
  public String w_doctype;
  public String w_sesso;
  public CPMNTChild[] m_MNTs = new CPMNTChild[]{};
  // variabile contenente i valori per i campi aggiunti e le proprietà dei rispettivi campi
  public XDCFieldValue[] extendedFields = new XDCFieldValue[]{};
}
