public class armt_settoreuicWV extends CallerBRImpl {
  /*  Dichiarazione delle variabili di lavoro: riflettono gli interventi dell'utente
                              o di una procedura nell'applicazione. Vengono utilizzate per aggiornare e
                              interrogare il database collegato.
                            */
  public String w_SETSINT;
  public String w_DESCRI;
  public String w_DASOT1;
  public String w_ASOT1;
  public String w_DASOT2;
  public String w_ASOT2;
  public String w_DASOT3;
  public String w_ASOT3;
  public String w_DASOT4;
  public String w_ASOT4;
  public String w_DASOT5;
  public String w_ASOT5;
  public String w_DASOT6;
  public String w_ASOT6;
  public String w_DASOT7;
  public String w_ASOT7;
  public String w_DASOT8;
  public String w_ASOT8;
  public String w_DASOT9;
  public String w_ASOT9;
  public String w_DASOT10;
  public String w_ASOT10;
  public String w_DASOT11;
  public String w_ASOT11;
  public String w_DASOT12;
  public String w_ASOT12;
  public java.sql.Date w_DATAINI;
  public java.sql.Date w_DATAFINE;
  public double w_IDSETSIN;
  public String w_DAGRU1;
  public String w_AGRU1;
  public String w_DAGRU2;
  public String w_AGRU2;
  public String w_DAGRU3;
  public String w_AGRU3;
  public String w_DAGRU4;
  public String w_AGRU4;
  public String w_DAGRU5;
  public String w_AGRU5;
  public String w_DAGRU6;
  public String w_AGRU6;
  public String w_DAATE2;
  public String w_AATE2;
  public String w_DAATE3;
  public String w_AATE3;
  public String w_DAATE4;
  public String w_AATE4;
  public String w_DAATE5;
  public String w_AATE5;
  public String w_DAATE6;
  public String w_AATE6;
  public String w_DAATE1;
  public String w_AATE1;
  public String w_descg1;
  public String w_descg2;
  public String w_descg3;
  public String w_descg4;
  public String w_descg5;
  public String w_descg6;
  public String w_descg7;
  public String w_descg8;
  public String w_descg9;
  public String w_descg10;
  public String w_descsg1;
  public String w_descsg2;
  public String w_descsg3;
  public String w_descsg4;
  public String w_descsg5;
  public String w_descsg6;
  public String w_descsg7;
  public String w_descsg8;
  public String w_descsg9;
  public String w_descsg10;
  public String w_descsg11;
  public String w_descsg12;
  public String w_descg11;
  public String w_descg12;
  public String w_descsg13;
  public String w_descsg14;
  public String w_descsg15;
  public String w_descsg16;
  public String w_descsg17;
  public String w_descsg18;
  public String w_descsg19;
  public String w_descsg20;
  public String w_descsg21;
  public String w_descsg22;
  public String w_descsg23;
  public String w_descsg24;
  public CPMNTChild[] m_MNTs = new CPMNTChild[]{};
  // variabile contenente i valori per i campi aggiunti e le proprietà dei rispettivi campi
  public XDCFieldValue[] extendedFields = new XDCFieldValue[]{};
}
