function arrt_modopen1() {
var w_ragione;
var w_datarett;
var w_newdate;
var w_newdatec;
var w_newintest;
var w_olddata;
var w_olddatac;
var w_oldfile;
var w_oldidbase;
var w_oldintest;
var w_oldprog;
var w_oldrappo;
var w_oldnumrig;
var w_tipochg;
var w_xcap;
var w_xcfestero;
var w_xcodfisc;
var w_xcognome;
var w_xdatnasc;
var w_xdesccit;
var w_xdessta;
var w_xnascomun;
var w_xnasstato;
var w_xnome;
var w_xpaese;
var w_xprovincia;
var w_xragnew;
var w_xragold;
var w_xsesso;
var w_xtipinter;
var w_xtipopers;
var w_idesito;
var m_Caller
arrt_modopen1._p=_rargs(arguments,{eval:function(e){eval(e)}})
w_ragione=m_Caller.GetString('w_ragione','C',0,0);
w_datarett=m_Caller.GetDate('w_datarett','D',0,0);
w_newdate=m_Caller.GetDate('w_newdate','D',0,0);
w_newdatec=m_Caller.GetDate('w_newdatec','D',0,0);
w_newintest=m_Caller.GetString('w_newintest','C',0,0);
w_olddata=m_Caller.GetDate('w_olddata','D',0,0);
w_olddatac=m_Caller.GetDate('w_olddatac','D',0,0);
w_oldfile=m_Caller.GetString('w_oldfile','C',0,0);
w_oldidbase=m_Caller.GetString('w_oldidbase','C',0,0);
w_oldintest=m_Caller.GetString('w_oldintest','C',0,0);
w_oldprog=m_Caller.GetString('w_oldprog','C',0,0);
w_oldrappo=m_Caller.GetString('w_oldrappo','C',0,0);
w_oldnumrig=m_Caller.GetNumber('w_oldnumrig','N',0,0);
w_tipochg=m_Caller.GetString('w_tipochg','C',0,0);
w_xcap=m_Caller.GetString('w_xcap','C',0,0);
w_xcfestero=m_Caller.GetNumber('w_xcfestero','N',0,0);
w_xcodfisc=m_Caller.GetString('w_xcodfisc','C',0,0);
w_xcognome=m_Caller.GetString('w_xcognome','C',0,0);
w_xdatnasc=m_Caller.GetDate('w_xdatnasc','D',0,0);
w_xdesccit=m_Caller.GetString('w_xdesccit','C',0,0);
w_xdessta=m_Caller.GetString('w_xdessta','C',0,0);
w_xnascomun=m_Caller.GetString('w_xnascomun','C',0,0);
w_xnasstato=m_Caller.GetString('w_xnasstato','C',0,0);
w_xnome=m_Caller.GetString('w_xnome','C',0,0);
w_xpaese=m_Caller.GetString('w_xpaese','C',0,0);
w_xprovincia=m_Caller.GetString('w_xprovincia','C',0,0);
w_xragnew=m_Caller.GetString('w_xragnew','C',0,0);
w_xragold=m_Caller.GetString('w_xragold','C',0,0);
w_xsesso=m_Caller.GetString('w_xsesso','C',0,0);
w_xtipinter=m_Caller.GetString('w_xtipinter','C',0,0);
w_xtipopers=m_Caller.GetString('w_xtipopers','C',0,0);
w_idesito=m_Caller.GetString('w_idesito','C',0,0);
arrt_modopen1._s=new BatchJavascript();
if (Ne(typeof(document.FSender),'undefined') && Ne(typeof(document.FSender.m_cRegionalSettings),'undefined')) {
arrt_modopen1._s.SetParameterString('m_cRegionalSettings',document.FSender.m_cRegionalSettings.value);
}
arrt_modopen1._s.SetCallerStringVar('w_ragione',WtA(w_ragione,'C'));
arrt_modopen1._s.SetCallerStringVar('w_datarett',WtA(w_datarett,'D'));
arrt_modopen1._s.SetCallerStringVar('w_newdate',WtA(w_newdate,'D'));
arrt_modopen1._s.SetCallerStringVar('w_newdatec',WtA(w_newdatec,'D'));
arrt_modopen1._s.SetCallerStringVar('w_newintest',WtA(w_newintest,'C'));
arrt_modopen1._s.SetCallerStringVar('w_olddata',WtA(w_olddata,'D'));
arrt_modopen1._s.SetCallerStringVar('w_olddatac',WtA(w_olddatac,'D'));
arrt_modopen1._s.SetCallerStringVar('w_oldfile',WtA(w_oldfile,'C'));
arrt_modopen1._s.SetCallerStringVar('w_oldidbase',WtA(w_oldidbase,'C'));
arrt_modopen1._s.SetCallerStringVar('w_oldintest',WtA(w_oldintest,'C'));
arrt_modopen1._s.SetCallerStringVar('w_oldprog',WtA(w_oldprog,'C'));
arrt_modopen1._s.SetCallerStringVar('w_oldrappo',WtA(w_oldrappo,'C'));
arrt_modopen1._s.SetCallerStringVar('w_oldnumrig',WtA(w_oldnumrig,'N'));
arrt_modopen1._s.SetCallerStringVar('w_tipochg',WtA(w_tipochg,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xcap',WtA(w_xcap,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xcfestero',WtA(w_xcfestero,'N'));
arrt_modopen1._s.SetCallerStringVar('w_xcodfisc',WtA(w_xcodfisc,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xcognome',WtA(w_xcognome,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xdatnasc',WtA(w_xdatnasc,'D'));
arrt_modopen1._s.SetCallerStringVar('w_xdesccit',WtA(w_xdesccit,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xdessta',WtA(w_xdessta,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xnascomun',WtA(w_xnascomun,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xnasstato',WtA(w_xnasstato,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xnome',WtA(w_xnome,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xpaese',WtA(w_xpaese,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xprovincia',WtA(w_xprovincia,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xragnew',WtA(w_xragnew,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xragold',WtA(w_xragold,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xsesso',WtA(w_xsesso,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xtipinter',WtA(w_xtipinter,'C'));
arrt_modopen1._s.SetCallerStringVar('w_xtipopers',WtA(w_xtipopers,'C'));
arrt_modopen1._s.SetCallerStringVar('w_idesito',WtA(w_idesito,'C'));
arrt_modopen1._s.SetParameterString('m_bApplet','true');
arrt_modopen1._s.CallServlet('arrt_modopen1');
m_Caller.SetString('w_ragione','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_ragione'));
m_Caller.SetDate('w_datarett','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_datarett')));
m_Caller.SetDate('w_newdate','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_newdate')));
m_Caller.SetDate('w_newdatec','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_newdatec')));
m_Caller.SetString('w_newintest','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_newintest'));
m_Caller.SetDate('w_olddata','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_olddata')));
m_Caller.SetDate('w_olddatac','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_olddatac')));
m_Caller.SetString('w_oldfile','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_oldfile'));
m_Caller.SetString('w_oldidbase','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_oldidbase'));
m_Caller.SetString('w_oldintest','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_oldintest'));
m_Caller.SetString('w_oldprog','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_oldprog'));
m_Caller.SetString('w_oldrappo','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_oldrappo'));
m_Caller.SetNumber('w_oldnumrig','N',0,0,arrt_modopen1._s.GetCallerDoubleVar('w_oldnumrig'));
m_Caller.SetString('w_tipochg','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_tipochg'));
m_Caller.SetString('w_xcap','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xcap'));
m_Caller.SetNumber('w_xcfestero','N',0,0,arrt_modopen1._s.GetCallerDoubleVar('w_xcfestero'));
m_Caller.SetString('w_xcodfisc','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xcodfisc'));
m_Caller.SetString('w_xcognome','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xcognome'));
m_Caller.SetDate('w_xdatnasc','D',0,0,DateFromApplet(arrt_modopen1._s.GetCallerDateVar('w_xdatnasc')));
m_Caller.SetString('w_xdesccit','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xdesccit'));
m_Caller.SetString('w_xdessta','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xdessta'));
m_Caller.SetString('w_xnascomun','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xnascomun'));
m_Caller.SetString('w_xnasstato','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xnasstato'));
m_Caller.SetString('w_xnome','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xnome'));
m_Caller.SetString('w_xpaese','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xpaese'));
m_Caller.SetString('w_xprovincia','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xprovincia'));
m_Caller.SetString('w_xragnew','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xragnew'));
m_Caller.SetString('w_xragold','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xragold'));
m_Caller.SetString('w_xsesso','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xsesso'));
m_Caller.SetString('w_xtipinter','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xtipinter'));
m_Caller.SetString('w_xtipopers','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_xtipopers'));
m_Caller.SetString('w_idesito','C',0,0,arrt_modopen1._s.GetCallerStringVar('w_idesito'));
if (Eq(typeof(m_bCalculating),'undefined') ||  ! (m_bCalculating)) {
m_cErrorFromRoutine=arrt_modopen1._s.errmsg;
}
if (Ne(typeof(CalledBatchEnd),'undefined')) {
CalledBatchEnd();
}
}
arrt_modopen1.CtxLoad_ = function(){return []}
