function arrt_wutrxchk_save() {
var w_TRXCODPRG;
var w_TRXCOGNOM;
var w_TRXNOME;
var w_TRXDOMICI;
var w_TRXFLGCF;
var w_TRXCODFIS;
var w_TRXLUONAS;
var w_TRXNUMDOC;
var w_TRXDATSCA;
var w_TRXDATRIL;
var w_TRXAUTRIL;
var w_TRXNAZRES;
var w_TRXCITRES;
var w_TRXTIPDOC;
var w_TRXDATOPE;
var w_TRXFLGCON;
var w_TRSSEGNO;
var w_TRXIMPORTO;
var w_TRXCONTAN;
var w_TRXUNIQUE;
var w_TRXCODDIP;
var w_TRXCOGCON;
var w_TRXNOMCON;
var w_TRXDESTIN;
var w_TRXMTCN;
var w_TRXDATNAS;
var w_TRXSESSO;
var w_TRXCODCAS;
var w_TRXRECTYPE;
var w_TRXCODMAG;
var w_TRXCODUNI;
var w_TRXFLGFOR;
var w_TRXTFINLAV;
var w_TRDFINLAV;
var w_TRFLGINLAV;
var w_TRXFLGAUA;
var w_TRXESITO;
var w_finalized;
var m_Caller
arrt_wutrxchk_save._p=_rargs(arguments,{eval:function(e){eval(e)}})
w_TRXCODPRG=m_Caller.GetNumber('w_TRXCODPRG','N',0,0);
w_TRXCOGNOM=m_Caller.GetString('w_TRXCOGNOM','C',0,0);
w_TRXNOME=m_Caller.GetString('w_TRXNOME','C',0,0);
w_TRXDOMICI=m_Caller.GetString('w_TRXDOMICI','C',0,0);
w_TRXFLGCF=m_Caller.GetString('w_TRXFLGCF','C',0,0);
w_TRXCODFIS=m_Caller.GetString('w_TRXCODFIS','C',0,0);
w_TRXLUONAS=m_Caller.GetString('w_TRXLUONAS','C',0,0);
w_TRXNUMDOC=m_Caller.GetString('w_TRXNUMDOC','C',0,0);
w_TRXDATSCA=m_Caller.GetDate('w_TRXDATSCA','D',0,0);
w_TRXDATRIL=m_Caller.GetDate('w_TRXDATRIL','D',0,0);
w_TRXAUTRIL=m_Caller.GetString('w_TRXAUTRIL','C',0,0);
w_TRXNAZRES=m_Caller.GetString('w_TRXNAZRES','C',0,0);
w_TRXCITRES=m_Caller.GetString('w_TRXCITRES','C',0,0);
w_TRXTIPDOC=m_Caller.GetString('w_TRXTIPDOC','C',0,0);
w_TRXDATOPE=m_Caller.GetDate('w_TRXDATOPE','D',0,0);
w_TRXFLGCON=m_Caller.GetString('w_TRXFLGCON','C',0,0);
w_TRSSEGNO=m_Caller.GetString('w_TRSSEGNO','C',0,0);
w_TRXIMPORTO=m_Caller.GetNumber('w_TRXIMPORTO','N',0,0);
w_TRXCONTAN=m_Caller.GetNumber('w_TRXCONTAN','N',0,0);
w_TRXUNIQUE=m_Caller.GetString('w_TRXUNIQUE','C',0,0);
w_TRXCODDIP=m_Caller.GetString('w_TRXCODDIP','C',0,0);
w_TRXCOGCON=m_Caller.GetString('w_TRXCOGCON','C',0,0);
w_TRXNOMCON=m_Caller.GetString('w_TRXNOMCON','C',0,0);
w_TRXDESTIN=m_Caller.GetString('w_TRXDESTIN','C',0,0);
w_TRXMTCN=m_Caller.GetString('w_TRXMTCN','C',0,0);
w_TRXDATNAS=m_Caller.GetDate('w_TRXDATNAS','D',0,0);
w_TRXSESSO=m_Caller.GetString('w_TRXSESSO','C',0,0);
w_TRXCODCAS=m_Caller.GetString('w_TRXCODCAS','C',0,0);
w_TRXRECTYPE=m_Caller.GetString('w_TRXRECTYPE','C',0,0);
w_TRXCODMAG=m_Caller.GetString('w_TRXCODMAG','C',0,0);
w_TRXCODUNI=m_Caller.GetString('w_TRXCODUNI','C',0,0);
w_TRXFLGFOR=m_Caller.GetString('w_TRXFLGFOR','C',0,0);
w_TRXTFINLAV=m_Caller.GetDateTime('w_TRXTFINLAV','T',0,0);
w_TRDFINLAV=m_Caller.GetDate('w_TRDFINLAV','D',0,0);
w_TRFLGINLAV=m_Caller.GetString('w_TRFLGINLAV','C',0,0);
w_TRXFLGAUA=m_Caller.GetString('w_TRXFLGAUA','C',0,0);
w_TRXESITO=m_Caller.GetString('w_TRXESITO','C',0,0);
w_finalized=m_Caller.GetString('w_finalized','C',0,0);
arrt_wutrxchk_save._s=new BatchJavascript();
if (Ne(typeof(document.FSender),'undefined') && Ne(typeof(document.FSender.m_cRegionalSettings),'undefined')) {
arrt_wutrxchk_save._s.SetParameterString('m_cRegionalSettings',document.FSender.m_cRegionalSettings.value);
}
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODPRG',WtA(w_TRXCODPRG,'N'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCOGNOM',WtA(w_TRXCOGNOM,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXNOME',WtA(w_TRXNOME,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDOMICI',WtA(w_TRXDOMICI,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXFLGCF',WtA(w_TRXFLGCF,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODFIS',WtA(w_TRXCODFIS,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXLUONAS',WtA(w_TRXLUONAS,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXNUMDOC',WtA(w_TRXNUMDOC,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDATSCA',WtA(w_TRXDATSCA,'D'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDATRIL',WtA(w_TRXDATRIL,'D'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXAUTRIL',WtA(w_TRXAUTRIL,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXNAZRES',WtA(w_TRXNAZRES,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCITRES',WtA(w_TRXCITRES,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXTIPDOC',WtA(w_TRXTIPDOC,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDATOPE',WtA(w_TRXDATOPE,'D'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXFLGCON',WtA(w_TRXFLGCON,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRSSEGNO',WtA(w_TRSSEGNO,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXIMPORTO',WtA(w_TRXIMPORTO,'N'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCONTAN',WtA(w_TRXCONTAN,'N'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXUNIQUE',WtA(w_TRXUNIQUE,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODDIP',WtA(w_TRXCODDIP,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCOGCON',WtA(w_TRXCOGCON,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXNOMCON',WtA(w_TRXNOMCON,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDESTIN',WtA(w_TRXDESTIN,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXMTCN',WtA(w_TRXMTCN,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXDATNAS',WtA(w_TRXDATNAS,'D'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXSESSO',WtA(w_TRXSESSO,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODCAS',WtA(w_TRXCODCAS,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXRECTYPE',WtA(w_TRXRECTYPE,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODMAG',WtA(w_TRXCODMAG,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXCODUNI',WtA(w_TRXCODUNI,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXFLGFOR',WtA(w_TRXFLGFOR,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXTFINLAV',WtA(w_TRXTFINLAV,'T'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRDFINLAV',WtA(w_TRDFINLAV,'D'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRFLGINLAV',WtA(w_TRFLGINLAV,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXFLGAUA',WtA(w_TRXFLGAUA,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_TRXESITO',WtA(w_TRXESITO,'C'));
arrt_wutrxchk_save._s.SetCallerStringVar('w_finalized',WtA(w_finalized,'C'));
arrt_wutrxchk_save._s.SetParameterString('m_bApplet','true');
arrt_wutrxchk_save._s.CallServlet('arrt_wutrxchk_save');
m_Caller.SetNumber('w_TRXCODPRG','N',0,0,arrt_wutrxchk_save._s.GetCallerDoubleVar('w_TRXCODPRG'));
m_Caller.SetString('w_TRXCOGNOM','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCOGNOM'));
m_Caller.SetString('w_TRXNOME','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXNOME'));
m_Caller.SetString('w_TRXDOMICI','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXDOMICI'));
m_Caller.SetString('w_TRXFLGCF','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXFLGCF'));
m_Caller.SetString('w_TRXCODFIS','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCODFIS'));
m_Caller.SetString('w_TRXLUONAS','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXLUONAS'));
m_Caller.SetString('w_TRXNUMDOC','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXNUMDOC'));
m_Caller.SetDate('w_TRXDATSCA','D',0,0,DateFromApplet(arrt_wutrxchk_save._s.GetCallerDateVar('w_TRXDATSCA')));
m_Caller.SetDate('w_TRXDATRIL','D',0,0,DateFromApplet(arrt_wutrxchk_save._s.GetCallerDateVar('w_TRXDATRIL')));
m_Caller.SetString('w_TRXAUTRIL','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXAUTRIL'));
m_Caller.SetString('w_TRXNAZRES','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXNAZRES'));
m_Caller.SetString('w_TRXCITRES','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCITRES'));
m_Caller.SetString('w_TRXTIPDOC','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXTIPDOC'));
m_Caller.SetDate('w_TRXDATOPE','D',0,0,DateFromApplet(arrt_wutrxchk_save._s.GetCallerDateVar('w_TRXDATOPE')));
m_Caller.SetString('w_TRXFLGCON','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXFLGCON'));
m_Caller.SetString('w_TRSSEGNO','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRSSEGNO'));
m_Caller.SetNumber('w_TRXIMPORTO','N',0,0,arrt_wutrxchk_save._s.GetCallerDoubleVar('w_TRXIMPORTO'));
m_Caller.SetNumber('w_TRXCONTAN','N',0,0,arrt_wutrxchk_save._s.GetCallerDoubleVar('w_TRXCONTAN'));
m_Caller.SetString('w_TRXUNIQUE','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXUNIQUE'));
m_Caller.SetString('w_TRXCODDIP','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCODDIP'));
m_Caller.SetString('w_TRXCOGCON','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCOGCON'));
m_Caller.SetString('w_TRXNOMCON','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXNOMCON'));
m_Caller.SetString('w_TRXDESTIN','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXDESTIN'));
m_Caller.SetString('w_TRXMTCN','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXMTCN'));
m_Caller.SetDate('w_TRXDATNAS','D',0,0,DateFromApplet(arrt_wutrxchk_save._s.GetCallerDateVar('w_TRXDATNAS')));
m_Caller.SetString('w_TRXSESSO','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXSESSO'));
m_Caller.SetString('w_TRXCODCAS','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCODCAS'));
m_Caller.SetString('w_TRXRECTYPE','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXRECTYPE'));
m_Caller.SetString('w_TRXCODMAG','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCODMAG'));
m_Caller.SetString('w_TRXCODUNI','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXCODUNI'));
m_Caller.SetString('w_TRXFLGFOR','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXFLGFOR'));
m_Caller.SetDateTime('w_TRXTFINLAV','T',0,0,DateTimeFromApplet(arrt_wutrxchk_save._s.GetCallerDateTimeVar('w_TRXTFINLAV')));
m_Caller.SetDate('w_TRDFINLAV','D',0,0,DateFromApplet(arrt_wutrxchk_save._s.GetCallerDateVar('w_TRDFINLAV')));
m_Caller.SetString('w_TRFLGINLAV','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRFLGINLAV'));
m_Caller.SetString('w_TRXFLGAUA','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXFLGAUA'));
m_Caller.SetString('w_TRXESITO','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_TRXESITO'));
m_Caller.SetString('w_finalized','C',0,0,arrt_wutrxchk_save._s.GetCallerStringVar('w_finalized'));
if (Eq(typeof(m_bCalculating),'undefined') ||  ! (m_bCalculating)) {
m_cErrorFromRoutine=arrt_wutrxchk_save._s.errmsg;
}
if (Ne(typeof(CalledBatchEnd),'undefined')) {
CalledBatchEnd();
}
}
arrt_wutrxchk_save.CtxLoad_ = function(){return []}
