function arrt_cgo_moduli_test() {
var w_STATOREG;
var w_IDBASE;
var w_NUMPROG;
var w_DESCRI;
var w_CITINT;
var w_CITDIP;
var w_PROVDIP;
var w_CABDIP;
var w_PROVINT;
var w_CABINT;
var w_TIPOPERS;
var w_MEZPAGAM;
var w_IBAN;
var w_CFESTERO;
var w_CODFISC;
var w_COGNOME;
var w_NOME;
var w_RAGSOC;
var w_DESCCIT;
var w_PROVINCIA;
var w_CAP;
var w_CODCAB;
var w_DOMICILIO;
var w_PAESE;
var w_NASCOMUN;
var w_TIPINTER;
var w_SESSO;
var w_NASSTATO;
var w_DATANASC;
var w_TIPODOC;
var w_NUMDOCUM;
var w_DATARILASC;
var w_DATAVALI;
var w_AUTRILASC;
var w_SOTGRUP;
var w_RAMOGRUP;
var w_SETTSINT;
var w_PEP;
var w_SNAINUMOPE;
var w_DATAOPE;
var w_DATAREG;
var w_FLAGCONT;
var w_TIPOOPRAP;
var w_CODANA;
var w_CODVOC;
var w_VALUTA;
var w_CAMBIO;
var w_CONNESCLI;
var w_CONNESBEN;
var w_C_RAG;
var w_C_CTA;
var w_C_PRV;
var w_C_CAP;
var w_C_CAB;
var w_C_IND;
var w_C_STA;
var w_CODINTER;
var w_CODDIPE;
var w_DESCCITDIP;
var w_SEGNO;
var w_FLAGFRAZ;
var w_COLLEG;
var w_PROVINCIADIP;
var w_CODCABDIP;
var w_TOTLIRE;
var w_TOTCONT;
var w_CACODICE;
var w_CAIDBIGLIETTO;
var w_CAFLGOPE;
var w_ATTIV;
var w_MIDBIGLIETTO;
var w_CODTRANSZ;
var m_Caller
arrt_cgo_moduli_test._p=_rargs(arguments,{eval:function(e){eval(e)}})
w_STATOREG=m_Caller.GetString('w_STATOREG','C',0,0);
w_IDBASE=m_Caller.GetString('w_IDBASE','C',0,0);
w_NUMPROG=m_Caller.GetString('w_NUMPROG','C',0,0);
w_DESCRI=m_Caller.GetString('w_DESCRI','C',0,0);
w_CITINT=m_Caller.GetString('w_CITINT','C',0,0);
w_CITDIP=m_Caller.GetString('w_CITDIP','C',0,0);
w_PROVDIP=m_Caller.GetString('w_PROVDIP','C',0,0);
w_CABDIP=m_Caller.GetString('w_CABDIP','C',0,0);
w_PROVINT=m_Caller.GetString('w_PROVINT','C',0,0);
w_CABINT=m_Caller.GetString('w_CABINT','C',0,0);
w_TIPOPERS=m_Caller.GetString('w_TIPOPERS','C',0,0);
w_MEZPAGAM=m_Caller.GetString('w_MEZPAGAM','C',0,0);
w_IBAN=m_Caller.GetString('w_IBAN','C',0,0);
w_CFESTERO=m_Caller.GetNumber('w_CFESTERO','N',0,0);
w_CODFISC=m_Caller.GetString('w_CODFISC','C',0,0);
w_COGNOME=m_Caller.GetString('w_COGNOME','C',0,0);
w_NOME=m_Caller.GetString('w_NOME','C',0,0);
w_RAGSOC=m_Caller.GetString('w_RAGSOC','C',0,0);
w_DESCCIT=m_Caller.GetString('w_DESCCIT','C',0,0);
w_PROVINCIA=m_Caller.GetString('w_PROVINCIA','C',0,0);
w_CAP=m_Caller.GetString('w_CAP','C',0,0);
w_CODCAB=m_Caller.GetString('w_CODCAB','C',0,0);
w_DOMICILIO=m_Caller.GetString('w_DOMICILIO','C',0,0);
w_PAESE=m_Caller.GetString('w_PAESE','C',0,0);
w_NASCOMUN=m_Caller.GetString('w_NASCOMUN','C',0,0);
w_TIPINTER=m_Caller.GetString('w_TIPINTER','C',0,0);
w_SESSO=m_Caller.GetString('w_SESSO','C',0,0);
w_NASSTATO=m_Caller.GetString('w_NASSTATO','C',0,0);
w_DATANASC=m_Caller.GetDate('w_DATANASC','D',0,0);
w_TIPODOC=m_Caller.GetString('w_TIPODOC','C',0,0);
w_NUMDOCUM=m_Caller.GetString('w_NUMDOCUM','C',0,0);
w_DATARILASC=m_Caller.GetDate('w_DATARILASC','D',0,0);
w_DATAVALI=m_Caller.GetDate('w_DATAVALI','D',0,0);
w_AUTRILASC=m_Caller.GetString('w_AUTRILASC','C',0,0);
w_SOTGRUP=m_Caller.GetString('w_SOTGRUP','C',0,0);
w_RAMOGRUP=m_Caller.GetString('w_RAMOGRUP','C',0,0);
w_SETTSINT=m_Caller.GetString('w_SETTSINT','C',0,0);
w_PEP=m_Caller.GetString('w_PEP','C',0,0);
w_SNAINUMOPE=m_Caller.GetString('w_SNAINUMOPE','C',0,0);
w_DATAOPE=m_Caller.GetDate('w_DATAOPE','D',0,0);
w_DATAREG=m_Caller.GetDate('w_DATAREG','D',0,0);
w_FLAGCONT=m_Caller.GetString('w_FLAGCONT','C',0,0);
w_TIPOOPRAP=m_Caller.GetString('w_TIPOOPRAP','C',0,0);
w_CODANA=m_Caller.GetString('w_CODANA','C',0,0);
w_CODVOC=m_Caller.GetString('w_CODVOC','C',0,0);
w_VALUTA=m_Caller.GetString('w_VALUTA','C',0,0);
w_CAMBIO=m_Caller.GetNumber('w_CAMBIO','N',0,0);
w_CONNESCLI=m_Caller.GetString('w_CONNESCLI','C',0,0);
w_CONNESBEN=m_Caller.GetString('w_CONNESBEN','C',0,0);
w_C_RAG=m_Caller.GetString('w_C_RAG','C',0,0);
w_C_CTA=m_Caller.GetString('w_C_CTA','C',0,0);
w_C_PRV=m_Caller.GetString('w_C_PRV','C',0,0);
w_C_CAP=m_Caller.GetString('w_C_CAP','C',0,0);
w_C_CAB=m_Caller.GetString('w_C_CAB','C',0,0);
w_C_IND=m_Caller.GetString('w_C_IND','C',0,0);
w_C_STA=m_Caller.GetString('w_C_STA','C',0,0);
w_CODINTER=m_Caller.GetString('w_CODINTER','C',0,0);
w_CODDIPE=m_Caller.GetString('w_CODDIPE','C',0,0);
w_DESCCITDIP=m_Caller.GetString('w_DESCCITDIP','C',0,0);
w_SEGNO=m_Caller.GetString('w_SEGNO','C',0,0);
w_FLAGFRAZ=m_Caller.GetString('w_FLAGFRAZ','C',0,0);
w_COLLEG=m_Caller.GetString('w_COLLEG','C',0,0);
w_PROVINCIADIP=m_Caller.GetString('w_PROVINCIADIP','C',0,0);
w_CODCABDIP=m_Caller.GetString('w_CODCABDIP','C',0,0);
w_TOTLIRE=m_Caller.GetNumber('w_TOTLIRE','N',0,0);
w_TOTCONT=m_Caller.GetNumber('w_TOTCONT','N',0,0);
w_CACODICE=m_Caller.GetNumber('w_CACODICE','N',0,0);
w_CAIDBIGLIETTO=m_Caller.GetString('w_CAIDBIGLIETTO','C',0,0);
w_CAFLGOPE=m_Caller.GetString('w_CAFLGOPE','C',0,0);
w_ATTIV=m_Caller.GetString('w_ATTIV','C',0,0);
w_MIDBIGLIETTO=m_Caller.GetString('w_MIDBIGLIETTO','M',0,0);
w_CODTRANSZ=m_Caller.GetString('w_CODTRANSZ','C',0,0);
arrt_cgo_moduli_test._s=new BatchJavascript();
if (Ne(typeof(document.FSender),'undefined') && Ne(typeof(document.FSender.m_cRegionalSettings),'undefined')) {
arrt_cgo_moduli_test._s.SetParameterString('m_cRegionalSettings',document.FSender.m_cRegionalSettings.value);
}
arrt_cgo_moduli_test._s.SetCallerStringVar('w_STATOREG',WtA(w_STATOREG,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_IDBASE',WtA(w_IDBASE,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_NUMPROG',WtA(w_NUMPROG,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DESCRI',WtA(w_DESCRI,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CITINT',WtA(w_CITINT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CITDIP',WtA(w_CITDIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PROVDIP',WtA(w_PROVDIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CABDIP',WtA(w_CABDIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PROVINT',WtA(w_PROVINT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CABINT',WtA(w_CABINT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TIPOPERS',WtA(w_TIPOPERS,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_MEZPAGAM',WtA(w_MEZPAGAM,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_IBAN',WtA(w_IBAN,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CFESTERO',WtA(w_CFESTERO,'N'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODFISC',WtA(w_CODFISC,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_COGNOME',WtA(w_COGNOME,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_NOME',WtA(w_NOME,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_RAGSOC',WtA(w_RAGSOC,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DESCCIT',WtA(w_DESCCIT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PROVINCIA',WtA(w_PROVINCIA,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CAP',WtA(w_CAP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODCAB',WtA(w_CODCAB,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DOMICILIO',WtA(w_DOMICILIO,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PAESE',WtA(w_PAESE,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_NASCOMUN',WtA(w_NASCOMUN,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TIPINTER',WtA(w_TIPINTER,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_SESSO',WtA(w_SESSO,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_NASSTATO',WtA(w_NASSTATO,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DATANASC',WtA(w_DATANASC,'D'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TIPODOC',WtA(w_TIPODOC,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_NUMDOCUM',WtA(w_NUMDOCUM,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DATARILASC',WtA(w_DATARILASC,'D'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DATAVALI',WtA(w_DATAVALI,'D'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_AUTRILASC',WtA(w_AUTRILASC,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_SOTGRUP',WtA(w_SOTGRUP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_RAMOGRUP',WtA(w_RAMOGRUP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_SETTSINT',WtA(w_SETTSINT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PEP',WtA(w_PEP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_SNAINUMOPE',WtA(w_SNAINUMOPE,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DATAOPE',WtA(w_DATAOPE,'D'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DATAREG',WtA(w_DATAREG,'D'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_FLAGCONT',WtA(w_FLAGCONT,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TIPOOPRAP',WtA(w_TIPOOPRAP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODANA',WtA(w_CODANA,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODVOC',WtA(w_CODVOC,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_VALUTA',WtA(w_VALUTA,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CAMBIO',WtA(w_CAMBIO,'N'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CONNESCLI',WtA(w_CONNESCLI,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CONNESBEN',WtA(w_CONNESBEN,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_RAG',WtA(w_C_RAG,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_CTA',WtA(w_C_CTA,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_PRV',WtA(w_C_PRV,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_CAP',WtA(w_C_CAP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_CAB',WtA(w_C_CAB,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_IND',WtA(w_C_IND,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_C_STA',WtA(w_C_STA,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODINTER',WtA(w_CODINTER,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODDIPE',WtA(w_CODDIPE,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_DESCCITDIP',WtA(w_DESCCITDIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_SEGNO',WtA(w_SEGNO,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_FLAGFRAZ',WtA(w_FLAGFRAZ,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_COLLEG',WtA(w_COLLEG,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_PROVINCIADIP',WtA(w_PROVINCIADIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODCABDIP',WtA(w_CODCABDIP,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TOTLIRE',WtA(w_TOTLIRE,'N'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_TOTCONT',WtA(w_TOTCONT,'N'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CACODICE',WtA(w_CACODICE,'N'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CAIDBIGLIETTO',WtA(w_CAIDBIGLIETTO,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CAFLGOPE',WtA(w_CAFLGOPE,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_ATTIV',WtA(w_ATTIV,'C'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_MIDBIGLIETTO',WtA(w_MIDBIGLIETTO,'M'));
arrt_cgo_moduli_test._s.SetCallerStringVar('w_CODTRANSZ',WtA(w_CODTRANSZ,'C'));
arrt_cgo_moduli_test._s.SetParameterString('m_bApplet','true');
arrt_cgo_moduli_test._s.CallServlet('arrt_cgo_moduli_test');
m_Caller.SetString('w_STATOREG','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_STATOREG'));
m_Caller.SetString('w_IDBASE','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_IDBASE'));
m_Caller.SetString('w_NUMPROG','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_NUMPROG'));
m_Caller.SetString('w_DESCRI','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_DESCRI'));
m_Caller.SetString('w_CITINT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CITINT'));
m_Caller.SetString('w_CITDIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CITDIP'));
m_Caller.SetString('w_PROVDIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PROVDIP'));
m_Caller.SetString('w_CABDIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CABDIP'));
m_Caller.SetString('w_PROVINT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PROVINT'));
m_Caller.SetString('w_CABINT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CABINT'));
m_Caller.SetString('w_TIPOPERS','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_TIPOPERS'));
m_Caller.SetString('w_MEZPAGAM','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_MEZPAGAM'));
m_Caller.SetString('w_IBAN','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_IBAN'));
m_Caller.SetNumber('w_CFESTERO','N',0,0,arrt_cgo_moduli_test._s.GetCallerDoubleVar('w_CFESTERO'));
m_Caller.SetString('w_CODFISC','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODFISC'));
m_Caller.SetString('w_COGNOME','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_COGNOME'));
m_Caller.SetString('w_NOME','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_NOME'));
m_Caller.SetString('w_RAGSOC','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_RAGSOC'));
m_Caller.SetString('w_DESCCIT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_DESCCIT'));
m_Caller.SetString('w_PROVINCIA','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PROVINCIA'));
m_Caller.SetString('w_CAP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CAP'));
m_Caller.SetString('w_CODCAB','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODCAB'));
m_Caller.SetString('w_DOMICILIO','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_DOMICILIO'));
m_Caller.SetString('w_PAESE','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PAESE'));
m_Caller.SetString('w_NASCOMUN','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_NASCOMUN'));
m_Caller.SetString('w_TIPINTER','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_TIPINTER'));
m_Caller.SetString('w_SESSO','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_SESSO'));
m_Caller.SetString('w_NASSTATO','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_NASSTATO'));
m_Caller.SetDate('w_DATANASC','D',0,0,DateFromApplet(arrt_cgo_moduli_test._s.GetCallerDateVar('w_DATANASC')));
m_Caller.SetString('w_TIPODOC','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_TIPODOC'));
m_Caller.SetString('w_NUMDOCUM','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_NUMDOCUM'));
m_Caller.SetDate('w_DATARILASC','D',0,0,DateFromApplet(arrt_cgo_moduli_test._s.GetCallerDateVar('w_DATARILASC')));
m_Caller.SetDate('w_DATAVALI','D',0,0,DateFromApplet(arrt_cgo_moduli_test._s.GetCallerDateVar('w_DATAVALI')));
m_Caller.SetString('w_AUTRILASC','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_AUTRILASC'));
m_Caller.SetString('w_SOTGRUP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_SOTGRUP'));
m_Caller.SetString('w_RAMOGRUP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_RAMOGRUP'));
m_Caller.SetString('w_SETTSINT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_SETTSINT'));
m_Caller.SetString('w_PEP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PEP'));
m_Caller.SetString('w_SNAINUMOPE','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_SNAINUMOPE'));
m_Caller.SetDate('w_DATAOPE','D',0,0,DateFromApplet(arrt_cgo_moduli_test._s.GetCallerDateVar('w_DATAOPE')));
m_Caller.SetDate('w_DATAREG','D',0,0,DateFromApplet(arrt_cgo_moduli_test._s.GetCallerDateVar('w_DATAREG')));
m_Caller.SetString('w_FLAGCONT','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_FLAGCONT'));
m_Caller.SetString('w_TIPOOPRAP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_TIPOOPRAP'));
m_Caller.SetString('w_CODANA','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODANA'));
m_Caller.SetString('w_CODVOC','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODVOC'));
m_Caller.SetString('w_VALUTA','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_VALUTA'));
m_Caller.SetNumber('w_CAMBIO','N',0,0,arrt_cgo_moduli_test._s.GetCallerDoubleVar('w_CAMBIO'));
m_Caller.SetString('w_CONNESCLI','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CONNESCLI'));
m_Caller.SetString('w_CONNESBEN','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CONNESBEN'));
m_Caller.SetString('w_C_RAG','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_RAG'));
m_Caller.SetString('w_C_CTA','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_CTA'));
m_Caller.SetString('w_C_PRV','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_PRV'));
m_Caller.SetString('w_C_CAP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_CAP'));
m_Caller.SetString('w_C_CAB','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_CAB'));
m_Caller.SetString('w_C_IND','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_IND'));
m_Caller.SetString('w_C_STA','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_C_STA'));
m_Caller.SetString('w_CODINTER','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODINTER'));
m_Caller.SetString('w_CODDIPE','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODDIPE'));
m_Caller.SetString('w_DESCCITDIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_DESCCITDIP'));
m_Caller.SetString('w_SEGNO','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_SEGNO'));
m_Caller.SetString('w_FLAGFRAZ','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_FLAGFRAZ'));
m_Caller.SetString('w_COLLEG','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_COLLEG'));
m_Caller.SetString('w_PROVINCIADIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_PROVINCIADIP'));
m_Caller.SetString('w_CODCABDIP','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODCABDIP'));
m_Caller.SetNumber('w_TOTLIRE','N',0,0,arrt_cgo_moduli_test._s.GetCallerDoubleVar('w_TOTLIRE'));
m_Caller.SetNumber('w_TOTCONT','N',0,0,arrt_cgo_moduli_test._s.GetCallerDoubleVar('w_TOTCONT'));
m_Caller.SetNumber('w_CACODICE','N',0,0,arrt_cgo_moduli_test._s.GetCallerDoubleVar('w_CACODICE'));
m_Caller.SetString('w_CAIDBIGLIETTO','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CAIDBIGLIETTO'));
m_Caller.SetString('w_CAFLGOPE','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CAFLGOPE'));
m_Caller.SetString('w_ATTIV','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_ATTIV'));
m_Caller.SetString('w_MIDBIGLIETTO','M',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_MIDBIGLIETTO'));
m_Caller.SetString('w_CODTRANSZ','C',0,0,arrt_cgo_moduli_test._s.GetCallerStringVar('w_CODTRANSZ'));
if (Eq(typeof(m_bCalculating),'undefined') ||  ! (m_bCalculating)) {
m_cErrorFromRoutine=arrt_cgo_moduli_test._s.errmsg;
}
if (Ne(typeof(CalledBatchEnd),'undefined')) {
CalledBatchEnd();
}
}
arrt_cgo_moduli_test.CtxLoad_ = function(){return []}
